/**
 * NextStepsCard — practical next-steps footer rendered after every Emmaus response.
 *
 * Four step types with emoji icons:
 *   📖 read     — a specific Scripture passage (tap to open in Bible reader)
 *   🙏 pray     — a short prayer prompt (no navigation)
 *   🎧 listen   — a verified ICC sermon clip
 *                  • If audioUrl is present: shows "Watch" + "Listen" sub-buttons
 *                  • Otherwise: tapping opens YouTube at the absolute timestamp
 *   🚶 continue — a Journey or guide recommendation (tap to navigate)
 *
 * The "listen" step is ALWAYS injected from verified server-side data — it is
 * never generated by the LLM so sermon references are always real.
 */

import { useState } from 'react';
import { useLocation } from 'wouter';
import type { NextStepItem } from '@/lib/emmaus-client';
import { SermonAudioPlayer } from '@/components/SermonAudioPlayer';

interface NextStepsCardProps {
  steps: NextStepItem[];
}

const TYPE_META: Record<NextStepItem['type'], { emoji: string; label: string }> = {
  read:     { emoji: '📖', label: 'Read' },
  pray:     { emoji: '🙏', label: 'Pray' },
  listen:   { emoji: '🎧', label: 'Listen' },
  continue: { emoji: '🚶', label: 'Continue' },
};

interface PlayerState {
  audioUrl: string;
  startSeconds: number;
  title: string;
  speaker?: string;
  watchUrl?: string;
}

export function NextStepsCard({ steps }: NextStepsCardProps) {
  const [, setLocation] = useLocation();
  const [player, setPlayer] = useState<PlayerState | null>(null);

  if (!steps || steps.length === 0) return null;

  function handleStep(step: NextStepItem) {
    if (step.type === 'listen' && step.audioUrl) {
      // Open in-app audio player
      setPlayer({
        audioUrl: step.audioUrl,
        startSeconds: step.relativeStartSeconds ?? 0,
        title: step.text,
        speaker: step.speakerName,
        watchUrl: step.watchUrl ?? step.path,
      });
      return;
    }
    if (!step.path) return;
    if (step.path.startsWith('http')) {
      window.open(step.path, '_blank', 'noopener noreferrer');
    } else {
      setLocation(step.path);
    }
  }

  function handleWatch(step: NextStepItem) {
    const url = step.watchUrl ?? step.path;
    if (url) window.open(url, '_blank', 'noopener noreferrer');
  }

  return (
    <>
      <div className="rounded-xl border border-border bg-card p-4 space-y-3">
        <p className="text-[11px] font-semibold text-muted-foreground uppercase tracking-widest">
          Next steps
        </p>

        <div className="space-y-3">
          {steps.map((step, i) => {
            const meta = TYPE_META[step.type] ?? { emoji: '→', label: step.type };
            const hasAudio = step.type === 'listen' && !!step.audioUrl;
            const isClickable = !!step.path || hasAudio;

            const inner = (
              <div className="flex items-start gap-2.5">
                {/* Emoji icon */}
                <span
                  className="text-[18px] leading-none mt-0.5 shrink-0 select-none"
                  aria-hidden="true"
                >
                  {meta.emoji}
                </span>

                {/* Label + text + sub-actions */}
                <div className="flex-1 min-w-0">
                  <span className="text-[11px] font-bold text-muted-foreground uppercase tracking-wide mr-1.5">
                    {meta.label}
                  </span>
                  <span
                    className={[
                      'text-[14px] leading-snug',
                      isClickable && !hasAudio
                        ? 'text-primary font-medium underline-offset-2 hover:underline'
                        : hasAudio
                        ? 'text-foreground font-medium'
                        : 'text-foreground',
                    ].join(' ')}
                  >
                    {step.text}
                  </span>

                  {/* Watch + Listen buttons when audio is available */}
                  {hasAudio && (
                    <div className="flex items-center gap-2 mt-1.5 flex-wrap">
                      <button
                        onClick={(e) => { e.stopPropagation(); handleStep(step); }}
                        className="flex items-center gap-1 text-[12px] font-medium text-amber-700 dark:text-amber-400 bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800 px-2.5 py-1 rounded-full hover:bg-amber-100 dark:hover:bg-amber-900/40 transition-colors"
                      >
                        🎧 {step.relativeStartSeconds ? `Listen from ${formatSeconds(step.relativeStartSeconds)}` : 'Listen'}
                      </button>
                      {(step.watchUrl ?? step.path) && (
                        <button
                          onClick={(e) => { e.stopPropagation(); handleWatch(step); }}
                          className="flex items-center gap-1 text-[12px] text-muted-foreground hover:text-foreground transition-colors"
                        >
                          ▶ {step.absoluteStartSeconds ? `Watch from ${formatSeconds(step.absoluteStartSeconds)}` : 'Watch'}
                        </button>
                      )}
                    </div>
                  )}

                  {/* Watch hint for listen steps without audio */}
                  {step.type === 'listen' && !hasAudio && step.timestampSeconds !== undefined && (
                    <span className="block text-[12px] text-amber-700 dark:text-amber-400 mt-0.5">
                      ▶ Watch from {formatSeconds(step.timestampSeconds)}
                    </span>
                  )}
                </div>
              </div>
            );

            if (isClickable && !hasAudio) {
              return (
                <button
                  key={i}
                  onClick={() => handleStep(step)}
                  className="w-full text-left hover:opacity-75 transition-opacity"
                  aria-label={`${meta.label}: ${step.text}`}
                >
                  {inner}
                </button>
              );
            }

            return (
              <div key={i} role="listitem">
                {inner}
              </div>
            );
          })}
        </div>
      </div>

      {/* In-app audio player sheet */}
      {player && (
        <SermonAudioPlayer
          open={!!player}
          onClose={() => setPlayer(null)}
          audioUrl={player.audioUrl}
          startSeconds={player.startSeconds}
          title={player.title}
          speaker={player.speaker}
          watchUrl={player.watchUrl}
        />
      )}
    </>
  );
}

function formatSeconds(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) return `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
  return `${m}:${s.toString().padStart(2, '0')}`;
}
