/**
 * Startup migrations — idempotent data-model upgrades that run once on boot.
 *
 * Each migration targets a specific, named record and is guarded by a WHERE clause
 * so it is safe to re-run any number of times.
 */

import { db, pool } from "@workspace/db";
import { journeysTable } from "@workspace/db/schema";
import { and, eq, ne } from "drizzle-orm";
import { logger } from "./logger.js";
export async function runStartupMigrations(): Promise<void> {
  // ── Sermon Companion tables (2026-07) ─────────────────────────────────────────
  // Three tables for AI-generated sermon companions. sermon_id is text (not FK)
  // because sermons are stored in a JSON file, not a DB table.
  // ── sermon_companion.published_at column (2026-07) ──────────────────────────
  // Added after initial launch so companions can be sorted by publication date
  // in the member Next Steps endpoint.  ALTER TABLE … ADD COLUMN IF NOT EXISTS
  // is a no-op on subsequent boots.
  // ── sermon_companion_entry.sermon_link column (2026-07) ─────────────────────
  // Per-day timestamped YouTube URL generated by the grounding-rules companion
  // generator. Pre-grounding entries have this as ''.
  try {
    await pool.query(`
      ALTER TABLE sermon_companion_entry
        ADD COLUMN IF NOT EXISTS sermon_link text NOT NULL DEFAULT '';
    `);
    logger.info("Startup migration: sermon_companion_entry.sermon_link column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: sermon_companion_entry.sermon_link column failed (non-fatal)");
  }

  try {
    await pool.query(`
      ALTER TABLE sermon_companion
        ADD COLUMN IF NOT EXISTS published_at timestamp;
    `);
    logger.info("Startup migration: sermon_companion.published_at column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: sermon_companion.published_at column failed (non-fatal)");
  }

  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS sermon_companion (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        sermon_id text NOT NULL,
        title text NOT NULL DEFAULT '',
        number_of_days integer NOT NULL DEFAULT 5,
        status text NOT NULL DEFAULT 'Draft',
        created_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS sermon_companion_entry (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        companion_id uuid NOT NULL REFERENCES sermon_companion(id) ON DELETE CASCADE,
        day_number integer NOT NULL,
        title text NOT NULL DEFAULT '',
        scripture_reference text DEFAULT '',
        greeting text DEFAULT '',
        reflection text DEFAULT '',
        prayer text DEFAULT '',
        next_step text DEFAULT '',
        closing text DEFAULT '',
        status text NOT NULL DEFAULT 'Draft',
        created_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        UNIQUE (companion_id, day_number)
      );

      CREATE TABLE IF NOT EXISTS sermon_companion_progress (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id text NOT NULL,
        companion_id uuid NOT NULL REFERENCES sermon_companion(id) ON DELETE CASCADE,
        current_day integer NOT NULL DEFAULT 1,
        completed_days jsonb NOT NULL DEFAULT '[]',
        started_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        UNIQUE (user_id, companion_id)
      );
    `);
    logger.info("Startup migration: sermon companion tables created (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: sermon companion tables failed (non-fatal)");
  }


  // ── Daily Devotionals tables (2026-07) ───────────────────────────────────────
  // Create the three devotional tables idempotently. Drizzle schema is the source
  // of truth for column definitions; this migration only ensures the tables exist.
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS devotional_series (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        title text NOT NULL,
        description text DEFAULT '',
        series_type text NOT NULL DEFAULT 'general',
        status text NOT NULL DEFAULT 'Draft',
        published_at timestamp,
        created_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        created_by text
      );

      CREATE TABLE IF NOT EXISTS devotional_entries (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        series_id uuid NOT NULL REFERENCES devotional_series(id) ON DELETE CASCADE,
        day_number integer NOT NULL,
        title text NOT NULL DEFAULT '',
        scripture_reference text DEFAULT '',
        greeting text DEFAULT '',
        consider_this text DEFAULT '',
        prayer text DEFAULT '',
        next_step text DEFAULT '',
        closing text DEFAULT '',
        status text NOT NULL DEFAULT 'Draft',
        published_at timestamp,
        created_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        UNIQUE (series_id, day_number)
      );

      CREATE TABLE IF NOT EXISTS devotional_progress (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id text NOT NULL,
        series_id uuid NOT NULL REFERENCES devotional_series(id) ON DELETE CASCADE,
        current_day integer NOT NULL DEFAULT 1,
        completed_days jsonb NOT NULL DEFAULT '[]',
        started_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        UNIQUE (user_id, series_id)
      );
    `);
    logger.info("Startup migration: devotional tables created (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: devotional tables failed (non-fatal)");
  }


  // ── Daily Rhythm Architecture (2026-07) ──────────────────────────────────────
  // Promote "15-minutes-with-jesus" from journeyType "core" → "daily-rhythm".
  // The 'daily-rhythm' type is a permanent, never-ending daily practice;
  // 'core' remains valid for finite onboarding journeys.
  try {
    await db
      .update(journeysTable)
      .set({ journeyType: "daily-rhythm" })
      .where(
        and(
          eq(journeysTable.id, "15-minutes-with-jesus"),
          eq(journeysTable.journeyType, "core")
        )
      );
    logger.info("Startup migration: daily-rhythm type applied (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: daily-rhythm type failed (non-fatal)");
  }

  // ── Restore Daily Rhythm to Published (2026-07) ──────────────────────────────
  // The Daily Rhythm journey is a permanent, always-on practice.
  // If it was accidentally set to Archived via the editor, restore it to Published
  // so the Walk screen can always find it via listPublishedJourneys().
  try {
    await db
      .update(journeysTable)
      .set({ status: "Published" })
      .where(
        and(
          eq(journeysTable.id, "15-minutes-with-jesus"),
          eq(journeysTable.status, "Archived")
        )
      );
    logger.info("Startup migration: daily-rhythm status restored to Published (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: daily-rhythm status restore failed (non-fatal)");
  }

  // ── Rename sprint (2026-07) ──────────────────────────────────────────────────
  // Display title update: journey was formerly "15 Minutes with Jesus", now "10 Minutes with Jesus".
  // The journey ID ("15-minutes-with-jesus") and all member progress are preserved.
  // estimatedDuration updated to reflect the new invitational framing.
  try {
    await db
      .update(journeysTable)
      .set({
        title: "10 Minutes with Jesus",
        estimatedDuration: "10 min/day",
      })
      .where(
        and(
          eq(journeysTable.id, "15-minutes-with-jesus"),
          ne(journeysTable.title, "10 Minutes with Jesus")
        )
      );
    logger.info("Startup migration: title renamed to '10 Minutes with Jesus' (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: title rename failed (non-fatal)");
  }

  // ── Journey layer seed data (2026-07) ─────────────────────────────────────────
  // Creates the "New to Faith" starter collection and its first journey
  // "Coming to Jesus" with 7 empty days. Uses fixed UUIDs / slugs so
  // this migration is idempotent and re-runnable.
  //
  // Collection ID:  '00000000-0000-0000-0000-000000000010'
  // Journey ID:     'coming-to-jesus'
  try {
    await pool.query(`
      INSERT INTO collections
        (id, title, description, status, display_order, tags, created_at, updated_at)
      VALUES
        ('00000000-0000-0000-0000-000000000010',
         'New to Faith',
         'An introductory pathway for people just beginning their faith journey.',
         'Draft', 10, '[]', NOW(), NOW())
      ON CONFLICT (id) DO NOTHING;
    `);

    await pool.query(`
      INSERT INTO journeys
        (id, title, description, journey_type, status, collection_id,
         difficulty, estimated_duration, duration_days, tags,
         created_at, updated_at)
      VALUES
        ('coming-to-jesus',
         'Coming to Jesus',
         'A 7-day introduction to knowing Jesus — who he is, what he did, and how to follow him.',
         'core', 'Draft', '00000000-0000-0000-0000-000000000010',
         'Beginner', '5 min/day', 7, '["new believers","foundations"]',
         NOW(), NOW())
      ON CONFLICT (id) DO NOTHING;
    `);

    await pool.query(`
      INSERT INTO journey_steps
        (journey_id, day, title, status, created_at, updated_at)
      VALUES
        ('coming-to-jesus', 1, '', 'draft', NOW(), NOW()),
        ('coming-to-jesus', 2, '', 'draft', NOW(), NOW()),
        ('coming-to-jesus', 3, '', 'draft', NOW(), NOW()),
        ('coming-to-jesus', 4, '', 'draft', NOW(), NOW()),
        ('coming-to-jesus', 5, '', 'draft', NOW(), NOW()),
        ('coming-to-jesus', 6, '', 'draft', NOW(), NOW()),
        ('coming-to-jesus', 7, '', 'draft', NOW(), NOW())
      ON CONFLICT (journey_id, day) DO NOTHING;
    `);

    logger.info("Startup migration: 'New to Faith' collection + 'Coming to Jesus' journey seeded (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: journey layer seed data failed (non-fatal)");
  }

}
