/**
 * Startup migrations — idempotent data-model upgrades that run once on boot.
 *
 * Each migration targets a specific, named record and is guarded by a WHERE clause
 * so it is safe to re-run any number of times.
 */

import { db, pool } from "@workspace/db";
import { journeysTable } from "@workspace/db/schema";
import { and, eq } from "drizzle-orm";
import { logger } from "./logger.js";
import { repairStepStatuses } from "./journey-store.js";
import { setStartSharedReady } from "./feature-flags.js";
export async function runStartupMigrations(): Promise<void> {
  // ── Sermon Companion tables (2026-07) ─────────────────────────────────────────
  // Three tables for AI-generated sermon companions. sermon_id is text (not FK)
  // because sermons are stored in a JSON file, not a DB table.
  // ── sermon_companion.published_at column (2026-07) ──────────────────────────
  // Added after initial launch so companions can be sorted by publication date
  // in the member Next Steps endpoint.  ALTER TABLE … ADD COLUMN IF NOT EXISTS
  // is a no-op on subsequent boots.
  // ── sermon_companion_entry.sermon_link column (2026-07) ─────────────────────
  // Per-day timestamped YouTube URL generated by the grounding-rules companion
  // generator. Pre-grounding entries have this as ''.
  try {
    await pool.query(`
      ALTER TABLE sermon_companion_entry
        ADD COLUMN IF NOT EXISTS sermon_link text NOT NULL DEFAULT '';
    `);
    logger.info("Startup migration: sermon_companion_entry.sermon_link column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: sermon_companion_entry.sermon_link column failed (non-fatal)");
  }

  try {
    await pool.query(`
      ALTER TABLE sermon_companion
        ADD COLUMN IF NOT EXISTS published_at timestamp;
    `);
    logger.info("Startup migration: sermon_companion.published_at column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: sermon_companion.published_at column failed (non-fatal)");
  }

  try {
    await pool.query(`
      ALTER TABLE sermon_companion
        ADD COLUMN IF NOT EXISTS is_current_week boolean NOT NULL DEFAULT false;
    `);
    logger.info("Startup migration: sermon_companion.is_current_week column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: sermon_companion.is_current_week column failed (non-fatal)");
  }

  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS sermon_companion (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        sermon_id text NOT NULL,
        title text NOT NULL DEFAULT '',
        number_of_days integer NOT NULL DEFAULT 5,
        status text NOT NULL DEFAULT 'Draft',
        created_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS sermon_companion_entry (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        companion_id uuid NOT NULL REFERENCES sermon_companion(id) ON DELETE CASCADE,
        day_number integer NOT NULL,
        title text NOT NULL DEFAULT '',
        scripture_reference text DEFAULT '',
        greeting text DEFAULT '',
        reflection text DEFAULT '',
        prayer text DEFAULT '',
        next_step text DEFAULT '',
        closing text DEFAULT '',
        status text NOT NULL DEFAULT 'Draft',
        created_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        UNIQUE (companion_id, day_number)
      );

      CREATE TABLE IF NOT EXISTS sermon_companion_progress (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id text NOT NULL,
        companion_id uuid NOT NULL REFERENCES sermon_companion(id) ON DELETE CASCADE,
        current_day integer NOT NULL DEFAULT 1,
        completed_days jsonb NOT NULL DEFAULT '[]',
        status text NOT NULL DEFAULT 'active',
        started_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        UNIQUE (user_id, companion_id)
      );
    `);
    logger.info("Startup migration: sermon companion tables created (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: sermon companion tables failed (non-fatal)");
  }


  // ── Daily Devotionals tables (2026-07) ───────────────────────────────────────
  // Create the three devotional tables idempotently. Drizzle schema is the source
  // of truth for column definitions; this migration only ensures the tables exist.
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS devotional_series (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        title text NOT NULL,
        description text DEFAULT '',
        series_type text NOT NULL DEFAULT 'general',
        status text NOT NULL DEFAULT 'Draft',
        published_at timestamp,
        created_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        created_by text
      );

      CREATE TABLE IF NOT EXISTS devotional_entries (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        series_id uuid NOT NULL REFERENCES devotional_series(id) ON DELETE CASCADE,
        day_number integer NOT NULL,
        title text NOT NULL DEFAULT '',
        scripture_reference text DEFAULT '',
        greeting text DEFAULT '',
        consider_this text DEFAULT '',
        prayer text DEFAULT '',
        next_step text DEFAULT '',
        closing text DEFAULT '',
        status text NOT NULL DEFAULT 'Draft',
        published_at timestamp,
        created_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        UNIQUE (series_id, day_number)
      );

      CREATE TABLE IF NOT EXISTS devotional_progress (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id text NOT NULL,
        series_id uuid NOT NULL REFERENCES devotional_series(id) ON DELETE CASCADE,
        current_day integer NOT NULL DEFAULT 1,
        completed_days jsonb NOT NULL DEFAULT '[]',
        status text NOT NULL DEFAULT 'active',
        started_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        UNIQUE (user_id, series_id)
      );
    `);
    logger.info("Startup migration: devotional tables created (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: devotional tables failed (non-fatal)");
  }

  // ── Active Engagement Platform Rule: status columns (2026-07) ───────────────
  // Add engagement lifecycle status to the two progress tables that were created
  // without it. The user_journey_progress table already has this column.
  // Running AFTER both CREATE TABLE blocks so both tables exist on fresh installs.
  // The CREATE TABLE definitions above already include `status`, so these ALTER
  // TABLE calls are no-ops on fresh DBs; they backfill existing production rows.
  try {
    await pool.query(`
      ALTER TABLE devotional_progress
        ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active';
    `);
    logger.info("Startup migration: devotional_progress.status column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: devotional_progress.status column failed (non-fatal)");
  }

  try {
    await pool.query(`
      ALTER TABLE sermon_companion_progress
        ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active';
    `);
    logger.info("Startup migration: sermon_companion_progress.status column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: sermon_companion_progress.status column failed (non-fatal)");
  }

  // ── Daily Rhythm Architecture (2026-07) ──────────────────────────────────────
  // Promote "15-minutes-with-jesus" from journeyType "core" → "daily-rhythm".
  // The 'daily-rhythm' type is a permanent, never-ending daily practice;
  // 'core' remains valid for finite onboarding journeys.
  try {
    await db
      .update(journeysTable)
      .set({ journeyType: "daily-rhythm" })
      .where(
        and(
          eq(journeysTable.id, "15-minutes-with-jesus"),
          eq(journeysTable.journeyType, "core")
        )
      );
    logger.info("Startup migration: daily-rhythm type applied (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: daily-rhythm type failed (non-fatal)");
  }


  // ── User profiles table (2026-07) ────────────────────────────────────────────
  // Persistent name storage keyed by email address so a member's preferred name
  // survives localStorage clears, sign-out/sign-in cycles, and mobile OS cache
  // eviction. The table is intentionally minimal — only the name is stored here;
  // all other user state remains in the demo auth layer.
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS user_profiles (
        email TEXT PRIMARY KEY,
        preferred_name TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);
    logger.info("Startup migration: user_profiles table ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: user_profiles table failed (non-fatal)");
  }

  // ── Remove seeded scaffold data (2026-07) ─────────────────────────────────────
  // The "New to Faith" collection and "Coming to Jesus" journey were previously
  // seeded on every boot. They have been removed from the seed block and must
  // now be cleaned out of any environment where they were created. These DELETEs
  // are idempotent: if the records are already gone, nothing happens.
  //
  // Collection ID: '00000000-0000-0000-0000-000000000010'
  // Journey ID:    'coming-to-jesus'
  try {
    await pool.query(`
      DELETE FROM journey_steps WHERE journey_id = 'coming-to-jesus';
    `);
    await pool.query(`
      DELETE FROM journeys WHERE id = 'coming-to-jesus';
    `);
    await pool.query(`
      DELETE FROM collections WHERE id = '00000000-0000-0000-0000-000000000010';
    `);
    logger.info("Startup migration: seeded scaffold data removed (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: scaffold cleanup failed (non-fatal)");
  }

  // ── Walk Completion step type (2026-07) ──────────────────────────────────────
  // Adds is_completion_step boolean column to journey_steps so that "Journey
  // Complete" steps can be distinguished from numbered lesson steps.
  // The column defaults to false — existing steps are unaffected.
  // After adding the column, any existing step whose title matches common
  // completion-step patterns is automatically marked, and durationDays for
  // affected journeys is recomputed to exclude those steps.
  try {
    await pool.query(`
      ALTER TABLE journey_steps
        ADD COLUMN IF NOT EXISTS is_completion_step boolean NOT NULL DEFAULT false;
    `);
    logger.info("Startup migration: journey_steps.is_completion_step column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: is_completion_step column add failed (non-fatal)");
  }

  try {
    // Mark steps whose title matches known completion-step patterns.
    // This catches existing admin-authored "Journey Complete" / "Walk Complete" steps
    // and makes them invisible to the lesson list and progress calculations.
    await pool.query(`
      UPDATE journey_steps
         SET is_completion_step = true
       WHERE is_completion_step = false
         AND (
           LOWER(title) LIKE '%journey complete%'
        OR LOWER(title) LIKE '%walk complete%'
         );
    `);
    logger.info("Startup migration: completion step detection applied (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: completion step detection failed (non-fatal)");
  }

  try {
    // Recompute durationDays for every journey that has at least one completion step,
    // now that those steps are excluded from the lesson count.
    await pool.query(`
      UPDATE journeys j
         SET duration_days = (
               SELECT COALESCE(MAX(s.day), 0)
                 FROM journey_steps s
                WHERE s.journey_id = j.id
                  AND s.status = 'Published'
                  AND s.is_completion_step = false
             )
       WHERE EXISTS (
               SELECT 1 FROM journey_steps s2
                WHERE s2.journey_id = j.id
                  AND s2.is_completion_step = true
             );
    `);
    logger.info("Startup migration: durationDays recomputed for journeys with completion steps (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: durationDays recompute failed (non-fatal)");
  }

  // ── Rooms tables (2026-07) ───────────────────────────────────────────────────
  // Four tables for the invite-only Rooms feature. Invite codes are 7 random
  // uppercase letters; invite tokens are UUIDs (for one-click join links).
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS rooms (
        id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        name         TEXT NOT NULL,
        invite_code  CHAR(7) NOT NULL UNIQUE,
        invite_token UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
        created_by   TEXT NOT NULL,
        created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS room_members (
        room_id    UUID NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
        user_id    TEXT NOT NULL,
        role       TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
        joined_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        PRIMARY KEY (room_id, user_id)
      );

      CREATE INDEX IF NOT EXISTS room_members_room_id_idx ON room_members(room_id);
      CREATE INDEX IF NOT EXISTS room_members_user_id_idx ON room_members(user_id);

      CREATE TABLE IF NOT EXISTS room_messages (
        id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        room_id    UUID NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
        user_id    TEXT NOT NULL,
        body       TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE INDEX IF NOT EXISTS room_messages_room_id_idx ON room_messages(room_id);

      CREATE TABLE IF NOT EXISTS room_journeys (
        room_id    UUID NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
        journey_id TEXT NOT NULL,
        started_by TEXT NOT NULL,
        started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        PRIMARY KEY (room_id, journey_id)
      );

      CREATE INDEX IF NOT EXISTS room_journeys_room_id_idx ON room_journeys(room_id);
    `);
    logger.info("Startup migration: rooms tables created (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: rooms tables failed (non-fatal)");
  }

  // ── Repair journey step statuses (2026-07) ────────────────────────────────────
  // Root cause: createStep always defaulted to status="Draft" regardless of
  // parent journey status. Steps added to a Published journey after it was
  // published stayed Draft and were invisible to members.
  //
  // Fix: for every Draft step whose parent journey is Published, set status to
  // Published. Also retires the "created-in-god-s-image" placeholder journey
  // (one Untitled Step) to Draft so it no longer shadows the real walk.
  //
  // Idempotent: if all steps are already Published, the UPDATE matches 0 rows.
  // The createStep fix (status inherited from parent) means this will be a no-op
  // on every boot after the first successful run.
  try {
    const report = await repairStepStatuses();
    if (report.stepsPublished > 0 || report.placeholderJourneyRetired) {
      logger.info(
        { stepsPublished: report.stepsPublished, placeholderJourneyRetired: report.placeholderJourneyRetired },
        "Startup migration: journey step statuses repaired"
      );
    } else {
      logger.info("Startup migration: journey step statuses already correct (no-op)");
    }
  } catch (err) {
    logger.warn({ err }, "Startup migration: journey step status repair failed (non-fatal)");
  }

  // ── user_journey_progress unique constraint (2026-07) ─────────────────────
  // Required for the atomic shared-start endpoint (POST /rooms/start-shared).
  //
  // Multi-instance safety: a pg_advisory_lock serializes the deduplicate +
  // index-create steps across all API processes booting simultaneously.
  // Whichever process wins the lock runs the DDL; the others wait, then proceed
  // through CREATE UNIQUE INDEX IF NOT EXISTS (a no-op) and — critically —
  // verify the catalog independently.  Every process that sees indisunique=true
  // AND indisvalid=true sets its own in-memory flag, so no process is left
  // permanently serving 503 because another process did the real work.
  //
  // The lock is held only for the mutation phase (deduplicate + CREATE INDEX);
  // the catalog verify runs outside the lock so it reflects the committed state.
  const ADVISORY_LOCK_KEY = 7_391_852; // arbitrary fixed integer; unique to this migration
  // All advisory-lock work MUST use a single checked-out PoolClient so that
  // pg_advisory_lock, the DDL, and pg_advisory_unlock are guaranteed to run
  // on the same physical connection.  pool.query() does not guarantee connection
  // affinity across calls and must not be used here.
  const migClient = await pool.connect();
  try {
    // Acquire the session-scoped advisory lock on this connection.
    // Concurrent processes block here until the winning process releases.
    await migClient.query(`SELECT pg_advisory_lock($1)`, [ADVISORY_LOCK_KEY]);
    try {
      // Step 1: Deduplicate existing rows so CREATE UNIQUE INDEX cannot fail
      // due to pre-existing duplicates.  Keep the row with the highest
      // current_day, breaking ties by latest updated_at.
      await migClient.query(`
        DELETE FROM user_journey_progress
        WHERE id IN (
          SELECT id FROM (
            SELECT id,
              ROW_NUMBER() OVER (
                PARTITION BY user_id, journey_id
                ORDER BY current_day DESC, updated_at DESC
              ) AS rn
            FROM user_journey_progress
          ) t WHERE rn > 1
        );
      `);

      // Step 2: Create the unique index on the same connection.
      // IF NOT EXISTS is a no-op for processes that waited while the winner
      // already committed the index.
      await migClient.query(`
        CREATE UNIQUE INDEX IF NOT EXISTS uidx_user_journey_progress_user_journey
          ON user_journey_progress (user_id, journey_id);
      `);

      // Step 3: Verify from the catalog before releasing the lock.  Running the
      // verify on the same connection while the lock is held gives this process
      // a consistent view.  indisvalid guards against an index left in an
      // invalid state by a previous failed concurrent build.
      const verifyRes = await migClient.query(`
        SELECT 1
          FROM pg_index i
          JOIN pg_class c ON c.oid = i.indexrelid
         WHERE c.relname = 'uidx_user_journey_progress_user_journey'
           AND i.indisunique = true
           AND i.indisvalid  = true
      `);

      // Set the flag before releasing the lock so the endpoint becomes active
      // only after the constraint is confirmed on this connection.
      if (verifyRes.rows.length > 0) {
        setStartSharedReady();
        logger.info("Startup migration: user_journey_progress unique index verified and active — start-shared endpoint active");
      } else {
        logger.error("Startup migration: unique index exists but catalog reports it as invalid or non-unique — start-shared endpoint will return 503");
      }
    } finally {
      // Always release the advisory lock on the same connection so other
      // booting processes can proceed rather than blocking indefinitely.
      await migClient.query(`SELECT pg_advisory_unlock($1)`, [ADVISORY_LOCK_KEY]).catch(() => {});
    }
  } catch (err) {
    logger.error({ err }, "Startup migration: user_journey_progress unique index FAILED — start-shared endpoint will return 503 until resolved");
  } finally {
    // Return the connection to the pool regardless of outcome.
    migClient.release();
  }

}
