/**
 * Startup migrations — idempotent data-model upgrades that run once on boot.
 *
 * Each migration targets a specific, named record and is guarded by a WHERE clause
 * so it is safe to re-run any number of times.
 */

import { db, pool } from "@workspace/db";
import { journeysTable } from "@workspace/db/schema";
import { and, eq } from "drizzle-orm";
import { logger } from "./logger.js";
import { repairStepStatuses } from "./journey-store.js";
import { setStartSharedReady } from "./feature-flags.js";
import { verifySermonStore } from "./sermon-store.js";
export async function runStartupMigrations(): Promise<void> {
  // ── Sermon store diagnostic (runs every boot — confirms data is reachable) ──
  await verifySermonStore().catch((err) =>
    logger.warn({ err }, "Sermon store diagnostic failed (non-fatal)")
  );
  // ── Sermon Companion tables (2026-07) ─────────────────────────────────────────
  // Three tables for AI-generated sermon companions. sermon_id is text (not FK)
  // because sermons are stored in a JSON file, not a DB table.
  // ── sermon_companion.published_at column (2026-07) ──────────────────────────
  // Added after initial launch so companions can be sorted by publication date
  // in the member Next Steps endpoint.  ALTER TABLE … ADD COLUMN IF NOT EXISTS
  // is a no-op on subsequent boots.
  // ── sermon_companion_entry.sermon_link column (2026-07) ─────────────────────
  // Per-day timestamped YouTube URL generated by the grounding-rules companion
  // generator. Pre-grounding entries have this as ''.
  try {
    await pool.query(`
      ALTER TABLE sermon_companion_entry
        ADD COLUMN IF NOT EXISTS sermon_link text NOT NULL DEFAULT '';
    `);
    logger.info("Startup migration: sermon_companion_entry.sermon_link column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: sermon_companion_entry.sermon_link column failed (non-fatal)");
  }

  try {
    await pool.query(`
      ALTER TABLE sermon_companion
        ADD COLUMN IF NOT EXISTS published_at timestamp;
    `);
    logger.info("Startup migration: sermon_companion.published_at column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: sermon_companion.published_at column failed (non-fatal)");
  }

  try {
    await pool.query(`
      ALTER TABLE sermon_companion
        ADD COLUMN IF NOT EXISTS is_current_week boolean NOT NULL DEFAULT false;
    `);
    logger.info("Startup migration: sermon_companion.is_current_week column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: sermon_companion.is_current_week column failed (non-fatal)");
  }

  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS sermon_companion (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        sermon_id text NOT NULL,
        title text NOT NULL DEFAULT '',
        number_of_days integer NOT NULL DEFAULT 5,
        status text NOT NULL DEFAULT 'Draft',
        created_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS sermon_companion_entry (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        companion_id uuid NOT NULL REFERENCES sermon_companion(id) ON DELETE CASCADE,
        day_number integer NOT NULL,
        title text NOT NULL DEFAULT '',
        scripture_reference text DEFAULT '',
        greeting text DEFAULT '',
        reflection text DEFAULT '',
        prayer text DEFAULT '',
        next_step text DEFAULT '',
        closing text DEFAULT '',
        status text NOT NULL DEFAULT 'Draft',
        created_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        UNIQUE (companion_id, day_number)
      );

      CREATE TABLE IF NOT EXISTS sermon_companion_progress (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id text NOT NULL,
        companion_id uuid NOT NULL REFERENCES sermon_companion(id) ON DELETE CASCADE,
        current_day integer NOT NULL DEFAULT 1,
        completed_days jsonb NOT NULL DEFAULT '[]',
        status text NOT NULL DEFAULT 'active',
        started_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        UNIQUE (user_id, companion_id)
      );
    `);
    logger.info("Startup migration: sermon companion tables created (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: sermon companion tables failed (non-fatal)");
  }


  // ── Daily Devotionals tables (2026-07) ───────────────────────────────────────
  // Create the three devotional tables idempotently. Drizzle schema is the source
  // of truth for column definitions; this migration only ensures the tables exist.
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS devotional_series (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        title text NOT NULL,
        description text DEFAULT '',
        series_type text NOT NULL DEFAULT 'general',
        status text NOT NULL DEFAULT 'Draft',
        published_at timestamp,
        created_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        created_by text
      );

      CREATE TABLE IF NOT EXISTS devotional_entries (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        series_id uuid NOT NULL REFERENCES devotional_series(id) ON DELETE CASCADE,
        day_number integer NOT NULL,
        title text NOT NULL DEFAULT '',
        scripture_reference text DEFAULT '',
        greeting text DEFAULT '',
        consider_this text DEFAULT '',
        prayer text DEFAULT '',
        next_step text DEFAULT '',
        closing text DEFAULT '',
        status text NOT NULL DEFAULT 'Draft',
        published_at timestamp,
        created_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        UNIQUE (series_id, day_number)
      );

      CREATE TABLE IF NOT EXISTS devotional_progress (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id text NOT NULL,
        series_id uuid NOT NULL REFERENCES devotional_series(id) ON DELETE CASCADE,
        current_day integer NOT NULL DEFAULT 1,
        completed_days jsonb NOT NULL DEFAULT '[]',
        status text NOT NULL DEFAULT 'active',
        started_at timestamp NOT NULL DEFAULT NOW(),
        updated_at timestamp NOT NULL DEFAULT NOW(),
        UNIQUE (user_id, series_id)
      );
    `);
    logger.info("Startup migration: devotional tables created (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: devotional tables failed (non-fatal)");
  }

  // ── Active Engagement Platform Rule: status columns (2026-07) ───────────────
  // Add engagement lifecycle status to the two progress tables that were created
  // without it. The user_journey_progress table already has this column.
  // Running AFTER both CREATE TABLE blocks so both tables exist on fresh installs.
  // The CREATE TABLE definitions above already include `status`, so these ALTER
  // TABLE calls are no-ops on fresh DBs; they backfill existing production rows.
  try {
    await pool.query(`
      ALTER TABLE devotional_progress
        ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active';
    `);
    logger.info("Startup migration: devotional_progress.status column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: devotional_progress.status column failed (non-fatal)");
  }

  try {
    await pool.query(`
      ALTER TABLE sermon_companion_progress
        ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active';
    `);
    logger.info("Startup migration: sermon_companion_progress.status column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: sermon_companion_progress.status column failed (non-fatal)");
  }

  // ── Daily Rhythm Architecture (2026-07) ──────────────────────────────────────
  // Promote "15-minutes-with-jesus" from journeyType "core" → "daily-rhythm".
  // The 'daily-rhythm' type is a permanent, never-ending daily practice;
  // 'core' remains valid for finite onboarding journeys.
  try {
    await db
      .update(journeysTable)
      .set({ journeyType: "daily-rhythm" })
      .where(
        and(
          eq(journeysTable.id, "15-minutes-with-jesus"),
          eq(journeysTable.journeyType, "core")
        )
      );
    logger.info("Startup migration: daily-rhythm type applied (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: daily-rhythm type failed (non-fatal)");
  }


  // ── User profiles table (2026-07) ────────────────────────────────────────────
  // Persistent name storage keyed by email address so a member's preferred name
  // survives localStorage clears, sign-out/sign-in cycles, and mobile OS cache
  // eviction. The table is intentionally minimal — only the name is stored here;
  // all other user state remains in the demo auth layer.
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS user_profiles (
        email TEXT PRIMARY KEY,
        preferred_name TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);
    logger.info("Startup migration: user_profiles table ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: user_profiles table failed (non-fatal)");
  }

  // ── Remove seeded scaffold data (2026-07) ─────────────────────────────────────
  // The "New to Faith" collection and "Coming to Jesus" journey were previously
  // seeded on every boot. They have been removed from the seed block and must
  // now be cleaned out of any environment where they were created. These DELETEs
  // are idempotent: if the records are already gone, nothing happens.
  //
  // Collection ID: '00000000-0000-0000-0000-000000000010'
  // Journey ID:    'coming-to-jesus'
  try {
    await pool.query(`
      DELETE FROM journey_steps WHERE journey_id = 'coming-to-jesus';
    `);
    await pool.query(`
      DELETE FROM journeys WHERE id = 'coming-to-jesus';
    `);
    await pool.query(`
      DELETE FROM collections WHERE id = '00000000-0000-0000-0000-000000000010';
    `);
    logger.info("Startup migration: seeded scaffold data removed (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: scaffold cleanup failed (non-fatal)");
  }

  // ── Walk Completion step type (2026-07) ──────────────────────────────────────
  // Adds is_completion_step boolean column to journey_steps so that "Journey
  // Complete" steps can be distinguished from numbered lesson steps.
  // The column defaults to false — existing steps are unaffected.
  // After adding the column, any existing step whose title matches common
  // completion-step patterns is automatically marked, and durationDays for
  // affected journeys is recomputed to exclude those steps.
  try {
    await pool.query(`
      ALTER TABLE journey_steps
        ADD COLUMN IF NOT EXISTS is_completion_step boolean NOT NULL DEFAULT false;
    `);
    logger.info("Startup migration: journey_steps.is_completion_step column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: is_completion_step column add failed (non-fatal)");
  }

  try {
    // Mark steps whose title matches known completion-step patterns.
    // This catches existing admin-authored "Journey Complete" / "Walk Complete" steps
    // and makes them invisible to the lesson list and progress calculations.
    await pool.query(`
      UPDATE journey_steps
         SET is_completion_step = true
       WHERE is_completion_step = false
         AND (
           LOWER(title) LIKE '%journey complete%'
        OR LOWER(title) LIKE '%walk complete%'
         );
    `);
    logger.info("Startup migration: completion step detection applied (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: completion step detection failed (non-fatal)");
  }

  try {
    // Recompute durationDays for every journey that has at least one completion step,
    // now that those steps are excluded from the lesson count.
    await pool.query(`
      UPDATE journeys j
         SET duration_days = (
               SELECT COALESCE(MAX(s.day), 0)
                 FROM journey_steps s
                WHERE s.journey_id = j.id
                  AND s.status = 'Published'
                  AND s.is_completion_step = false
             )
       WHERE EXISTS (
               SELECT 1 FROM journey_steps s2
                WHERE s2.journey_id = j.id
                  AND s2.is_completion_step = true
             );
    `);
    logger.info("Startup migration: durationDays recomputed for journeys with completion steps (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: durationDays recompute failed (non-fatal)");
  }

  // ── Rooms tables (2026-07) ───────────────────────────────────────────────────
  // Four tables for the invite-only Rooms feature. Invite codes are 7 random
  // uppercase letters; invite tokens are UUIDs (for one-click join links).
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS rooms (
        id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        name         TEXT NOT NULL,
        invite_code  CHAR(7) NOT NULL UNIQUE,
        invite_token UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
        created_by   TEXT NOT NULL,
        created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS room_members (
        room_id    UUID NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
        user_id    TEXT NOT NULL,
        role       TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
        joined_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        PRIMARY KEY (room_id, user_id)
      );

      CREATE INDEX IF NOT EXISTS room_members_room_id_idx ON room_members(room_id);
      CREATE INDEX IF NOT EXISTS room_members_user_id_idx ON room_members(user_id);

      CREATE TABLE IF NOT EXISTS room_messages (
        id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        room_id    UUID NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
        user_id    TEXT NOT NULL,
        body       TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );

      CREATE INDEX IF NOT EXISTS room_messages_room_id_idx ON room_messages(room_id);

      CREATE TABLE IF NOT EXISTS room_journeys (
        room_id    UUID NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
        journey_id TEXT NOT NULL,
        started_by TEXT NOT NULL,
        started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        PRIMARY KEY (room_id, journey_id)
      );

      CREATE INDEX IF NOT EXISTS room_journeys_room_id_idx ON room_journeys(room_id);
    `);
    logger.info("Startup migration: rooms tables created (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: rooms tables failed (non-fatal)");
  }

  // ── Rooms description column (2026-07) ───────────────────────────────────────
  // Added after initial launch so Room creators can provide a brief description.
  // ALTER TABLE … ADD COLUMN IF NOT EXISTS is idempotent.
  try {
    await pool.query(`
      ALTER TABLE rooms
      ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT ''
    `);
    logger.info("Startup migration: rooms.description column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: rooms.description column failed (non-fatal)");
  }

  // ── Walk theme_color and version columns (2026-07) ───────────────────────────
  // theme_color — nullable VARCHAR(7) for hex brand colours on a Walk.
  // version     — integer, defaults to 1; incremented by the API on each publish.
  // Both are completely additive — existing rows are unaffected.
  try {
    await pool.query(`
      ALTER TABLE journeys
        ADD COLUMN IF NOT EXISTS theme_color VARCHAR(7),
        ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;
    `);
    logger.info("Startup migration: journeys.theme_color + version columns ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: journeys.theme_color / version columns failed (non-fatal)");
  }

  // ── Smart Content Indicators — notify_published_at + last_opened_at (2026-07) ──
  // IMPORTANT: must run before repairStepStatuses which queries the journeys table
  // via Drizzle (which now includes notify_published_at in the SELECT). If the column
  // doesn't exist when that query runs, it will fail with "column does not exist".
  // notify_published_at: set on content tables when admin opts-in to notifying members.
  // last_opened_at: set on progress tables when a member opens/views the content.
  // Both are nullable; null = feature not yet activated for that row.
  {
    const badgeAlters = [
      `ALTER TABLE journeys                  ADD COLUMN IF NOT EXISTS notify_published_at timestamptz`,
      `ALTER TABLE devotional_series         ADD COLUMN IF NOT EXISTS notify_published_at timestamptz`,
      `ALTER TABLE sermon_companion          ADD COLUMN IF NOT EXISTS notify_published_at timestamptz`,
      `ALTER TABLE user_journey_progress     ADD COLUMN IF NOT EXISTS last_opened_at timestamptz`,
      `ALTER TABLE devotional_progress       ADD COLUMN IF NOT EXISTS last_opened_at timestamptz`,
      `ALTER TABLE sermon_companion_progress ADD COLUMN IF NOT EXISTS last_opened_at timestamptz`,
    ];
    for (const sql of badgeAlters) {
      try {
        await pool.query(sql);
      } catch (err) {
        logger.warn({ err, sql }, "Startup migration: badge column alter failed (non-fatal)");
      }
    }
    logger.info("Startup migration: Smart Content Indicator columns ensured (idempotent)");
  }

  // ── Repair journey step statuses (2026-07) ────────────────────────────────────
  // Root cause: createStep always defaulted to status="Draft" regardless of
  // parent journey status. Steps added to a Published journey after it was
  // published stayed Draft and were invisible to members.
  //
  // Fix: for every Draft step whose parent journey is Published, set status to
  // Published. Also retires the "created-in-god-s-image" placeholder journey
  // (one Untitled Step) to Draft so it no longer shadows the real walk.
  //
  // Idempotent: if all steps are already Published, the UPDATE matches 0 rows.
  // The createStep fix (status inherited from parent) means this will be a no-op
  // on every boot after the first successful run.
  try {
    const report = await repairStepStatuses();
    if (report.stepsPublished > 0 || report.placeholderJourneyRetired) {
      logger.info(
        { stepsPublished: report.stepsPublished, placeholderJourneyRetired: report.placeholderJourneyRetired },
        "Startup migration: journey step statuses repaired"
      );
    } else {
      logger.info("Startup migration: journey step statuses already correct (no-op)");
    }
  } catch (err) {
    logger.warn({ err }, "Startup migration: journey step status repair failed (non-fatal)");
  }

  // ── user_journey_progress unique constraint (2026-07) ─────────────────────
  // Required for the atomic shared-start endpoint (POST /rooms/start-shared).
  //
  // Multi-instance safety: a pg_advisory_lock serializes the deduplicate +
  // index-create steps across all API processes booting simultaneously.
  // Whichever process wins the lock runs the DDL; the others wait, then proceed
  // through CREATE UNIQUE INDEX IF NOT EXISTS (a no-op) and — critically —
  // verify the catalog independently.  Every process that sees indisunique=true
  // AND indisvalid=true sets its own in-memory flag, so no process is left
  // permanently serving 503 because another process did the real work.
  //
  // The lock is held only for the mutation phase (deduplicate + CREATE INDEX);
  // the catalog verify runs outside the lock so it reflects the committed state.
  const ADVISORY_LOCK_KEY = 7_391_852; // arbitrary fixed integer; unique to this migration
  // All advisory-lock work MUST use a single checked-out PoolClient so that
  // pg_advisory_lock, the DDL, and pg_advisory_unlock are guaranteed to run
  // on the same physical connection.  pool.query() does not guarantee connection
  // affinity across calls and must not be used here.
  const migClient = await pool.connect();
  try {
    // Acquire the session-scoped advisory lock on this connection.
    // Concurrent processes block here until the winning process releases.
    await migClient.query(`SELECT pg_advisory_lock($1)`, [ADVISORY_LOCK_KEY]);
    try {
      // Step 1a: For duplicate (user_id, journey_id) pairs, merge all
      // completed_days arrays into the keeper row (highest current_day, then
      // latest updated_at) so that progress history is preserved before the
      // non-keeper rows are deleted.
      await migClient.query(`
        UPDATE user_journey_progress AS keeper
        SET completed_days = (
          SELECT COALESCE(
            jsonb_agg(DISTINCT val ORDER BY val),
            '[]'::jsonb
          )
          FROM (
            SELECT jsonb_array_elements(dup.completed_days) AS val
            FROM user_journey_progress dup
            WHERE dup.user_id    = keeper.user_id
              AND dup.journey_id = keeper.journey_id
          ) all_vals
        )
        WHERE keeper.id IN (
          SELECT DISTINCT ON (user_id, journey_id) id
          FROM user_journey_progress
          ORDER BY user_id, journey_id, current_day DESC, updated_at DESC
        )
        AND (
          SELECT count(*)
          FROM user_journey_progress x
          WHERE x.user_id = keeper.user_id AND x.journey_id = keeper.journey_id
        ) > 1
      `);

      // Step 1b: Delete every non-keeper row so CREATE UNIQUE INDEX cannot fail
      // due to pre-existing duplicates.
      await migClient.query(`
        DELETE FROM user_journey_progress
        WHERE id IN (
          SELECT id FROM (
            SELECT id,
              ROW_NUMBER() OVER (
                PARTITION BY user_id, journey_id
                ORDER BY current_day DESC, updated_at DESC
              ) AS rn
            FROM user_journey_progress
          ) t WHERE rn > 1
        )
      `);

      // Step 2: Create the unique index on the same connection.
      // IF NOT EXISTS is a no-op for processes that waited while the winner
      // already committed the index.
      await migClient.query(`
        CREATE UNIQUE INDEX IF NOT EXISTS uidx_user_journey_progress_user_journey
          ON user_journey_progress (user_id, journey_id)
      `);

      // Step 3: Verify from the catalog before releasing the lock.  Running the
      // verify on the same connection while the lock is held gives this process
      // a consistent view.  indisvalid guards against an index left in an
      // invalid state by a previous failed concurrent build.
      const verifyRes = await migClient.query(`
        SELECT 1
          FROM pg_index i
          JOIN pg_class c ON c.oid = i.indexrelid
         WHERE c.relname = 'uidx_user_journey_progress_user_journey'
           AND i.indisunique = true
           AND i.indisvalid  = true
      `);

      // Set the flag before releasing the lock so the endpoint becomes active
      // only after the constraint is confirmed on this connection.
      if (verifyRes.rows.length > 0) {
        setStartSharedReady();
        logger.info("Startup migration: user_journey_progress unique index verified and active — start-shared endpoint active");
      } else {
        logger.error("Startup migration: unique index exists but catalog reports it as invalid or non-unique — start-shared endpoint will return 503");
      }
    } finally {
      // Always release the advisory lock on the same connection so other
      // booting processes can proceed rather than blocking indefinitely.
      await migClient.query(`SELECT pg_advisory_unlock($1)`, [ADVISORY_LOCK_KEY]).catch(() => {});
    }
  } catch (err) {
    logger.error({ err }, "Startup migration: user_journey_progress unique index FAILED — start-shared endpoint will return 503 until resolved");
  } finally {
    // Return the connection to the pool regardless of outcome.
    migClient.release();
  }

  // ── Bible: persistent user annotation storage (2026-07) ────────────────────
  // Replaces the ephemeral in-memory Map in bible/store.ts. One JSONB row per
  // user; blob is identical to the shape used by BibleContext so the existing
  // PATCH /api/bible/data payload works without any client changes.
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS user_bible_data (
        user_id   text PRIMARY KEY,
        data      jsonb NOT NULL DEFAULT '{}',
        updated_at timestamp NOT NULL DEFAULT now()
      )
    `);
    logger.info("Startup migration: user_bible_data table ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: user_bible_data table failed (non-fatal)");
  }

  // ── Bible: cross references (2026-07) ─────────────────────────────────────
  // Stores cross-reference pairs between Bible verses, editable by admins.
  // Each row links a "from" verse to a "to" verse with an optional note.
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS bible_cross_references (
        id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        from_book_id      text NOT NULL,
        from_chapter      int  NOT NULL,
        from_verse        int  NOT NULL,
        to_book_id        text NOT NULL,
        to_chapter        int  NOT NULL,
        to_verse          int  NOT NULL,
        relationship_note text NOT NULL DEFAULT '',
        created_by        text NOT NULL DEFAULT '',
        created_at        timestamp NOT NULL DEFAULT now()
      );
      CREATE INDEX IF NOT EXISTS bible_cross_refs_from_idx
        ON bible_cross_references(from_book_id, from_chapter, from_verse);
      CREATE INDEX IF NOT EXISTS bible_cross_refs_to_idx
        ON bible_cross_references(to_book_id, to_chapter, to_verse);
    `);
    logger.info("Startup migration: bible_cross_references table ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: bible_cross_references table failed (non-fatal)");
  }

  // ── Bible: admin study notes (2026-07) ─────────────────────────────────────
  // Stores curator-authored study content per verse/passage. All fields are
  // optional text so the admin can fill in sections incrementally.
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS bible_study_notes (
        id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        book_id               text NOT NULL,
        chapter               int  NOT NULL,
        verse_start           int  NOT NULL,
        verse_end             int,
        title                 text NOT NULL DEFAULT '',
        content               text NOT NULL DEFAULT '',
        context_note          text NOT NULL DEFAULT '',
        historical_note       text NOT NULL DEFAULT '',
        original_language_note text NOT NULL DEFAULT '',
        jesus_connection      text NOT NULL DEFAULT '',
        apply_it              text NOT NULL DEFAULT '',
        status                text NOT NULL DEFAULT 'Draft'
          CHECK (status IN ('Draft','In Review','Published','Archived')),
        created_by            text NOT NULL DEFAULT '',
        updated_by            text NOT NULL DEFAULT '',
        created_at            timestamp NOT NULL DEFAULT now(),
        updated_at            timestamp NOT NULL DEFAULT now()
      )
    `);
    logger.info("Startup migration: bible_study_notes table ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: bible_study_notes table failed (non-fatal)");
  }

  // ── Bible: extend study notes with passage-level fields (2026-07) ──────────
  // Adds JSONB columns for cross-references, themes, people, places, sources,
  // psalm metadata. Idempotent: ADD COLUMN IF NOT EXISTS is safe to re-run.
  try {
    await pool.query(`
      ALTER TABLE bible_study_notes
        ADD COLUMN IF NOT EXISTS cross_references       jsonb NOT NULL DEFAULT '[]',
        ADD COLUMN IF NOT EXISTS key_themes             jsonb NOT NULL DEFAULT '[]',
        ADD COLUMN IF NOT EXISTS important_people       jsonb NOT NULL DEFAULT '[]',
        ADD COLUMN IF NOT EXISTS important_places       jsonb NOT NULL DEFAULT '[]',
        ADD COLUMN IF NOT EXISTS source_records         jsonb NOT NULL DEFAULT '[]',
        ADD COLUMN IF NOT EXISTS psalm_metadata         jsonb NOT NULL DEFAULT '{}',
        ADD COLUMN IF NOT EXISTS note_type              text  NOT NULL DEFAULT 'passage'
    `);
    logger.info("Startup migration: bible_study_notes extended columns ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: bible_study_notes column extension failed (non-fatal)");
  }

  // ── Bible: study-notes authoring fields (key_truth, reflection_question, related_scriptures) ──
  try {
    await pool.query(`
      ALTER TABLE bible_study_notes
        ADD COLUMN IF NOT EXISTS key_truth            text NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS reflection_question  text NOT NULL DEFAULT '',
        ADD COLUMN IF NOT EXISTS related_scriptures   text NOT NULL DEFAULT ''
    `);
    logger.info("Startup migration: bible_study_notes authoring columns ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: bible_study_notes authoring columns failed (non-fatal)");
  }

  // ── Bible: seed study notes if table is empty (2026-08) ──────────────────
  // Seeds 1,014 pre-authored notes from the bundled JSON when the DB has none.
  // Idempotent: only runs if COUNT(*) = 0. Safe to deploy multiple times.
  try {
    const { readFileSync } = await import('node:fs');
    const { fileURLToPath } = await import('node:url');
    const { dirname, resolve } = await import('node:path');
    // import.meta.url resolves to the esbuild bundle (dist/index.mjs).
    // The seed JSON is copied to dist/data/ by build.mjs, so the path is
    // sibling 'data/' from the bundle's own directory — NOT '../data/'.
    const seedPath = resolve(dirname(fileURLToPath(import.meta.url)), 'data/bible-study-notes-seed.json');
    type SeedNote = {
      book_id: string; chapter: number; verse_start: number; verse_end: number | null;
      title: string; content: string; context_note: string; historical_note: string;
      original_language_note: string; jesus_connection: string; apply_it: string; status: string;
      key_truth: string; reflection_question: string; related_scriptures: string;
    };
    const notes: SeedNote[] = JSON.parse(readFileSync(seedPath, 'utf-8')) as SeedNote[];

    const { rows: countRows } = await pool.query(`SELECT COUNT(*) AS n FROM bible_study_notes`);
    if (Number(countRows[0].n) === 0) {
      for (const n of notes) {
        await pool.query(
          `INSERT INTO bible_study_notes
             (book_id, chapter, verse_start, verse_end, title, content, context_note,
              historical_note, original_language_note, jesus_connection, apply_it,
              key_truth, reflection_question, related_scriptures,
              status, created_by, updated_by)
           VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,'seed','seed')
           ON CONFLICT DO NOTHING`,
          [
            n.book_id, n.chapter, n.verse_start,
            n.verse_end ?? null,
            n.title, n.content, n.context_note,
            n.historical_note, n.original_language_note,
            n.jesus_connection, n.apply_it,
            n.key_truth ?? '', n.reflection_question ?? '', n.related_scriptures ?? '',
            n.status,
          ]
        );
      }
      logger.info({ count: notes.length }, "Startup migration: bible_study_notes seeded from bundled JSON");
    } else {
      logger.info({ existing: countRows[0].n }, "Startup migration: bible_study_notes already populated, skipping seed");
    }

    // ── Backfill key_truth / reflection_question / related_scriptures on existing rows ──
    // Runs on every boot but is a no-op when all rows are already populated.
    // Matches by (book_id, chapter, verse_start) — the natural composite key used in seeding.
    let backfilled = 0;
    for (const n of notes) {
      if (!n.key_truth && !n.reflection_question && !n.related_scriptures) continue;
      const result = await pool.query(
        `UPDATE bible_study_notes
         SET key_truth         = $1,
             reflection_question = $2,
             related_scriptures  = $3,
             updated_at          = now()
         WHERE book_id = $4 AND chapter = $5 AND verse_start = $6
           AND (key_truth = '' OR key_truth IS NULL)`,
        [
          n.key_truth ?? '', n.reflection_question ?? '', n.related_scriptures ?? '',
          n.book_id, n.chapter, n.verse_start,
        ]
      );
      backfilled += result.rowCount ?? 0;
    }
    if (backfilled > 0) {
      logger.info({ backfilled }, "Startup migration: bible_study_notes key_truth/reflection/related_scriptures backfilled");
    } else {
      logger.info("Startup migration: bible_study_notes new authoring fields already populated, no backfill needed");
    }
  } catch (err) {
    logger.warn({ err }, "Startup migration: bible_study_notes seed/backfill failed (non-fatal)");
  }

  // ── Bible: study-notes unique index (2026-07) ─────────────────────────────
  // Required for ON CONFLICT (book_id, chapter, verse_start) in the generate
  // endpoint. Safe to re-run (CREATE UNIQUE INDEX IF NOT EXISTS).
  try {
    await pool.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS uidx_bible_study_notes_book_chapter_verse
        ON bible_study_notes (book_id, chapter, verse_start)
    `);
    logger.info("Startup migration: bible_study_notes unique index ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: bible_study_notes unique index failed (non-fatal)");
  }

  // ── Bible: book introductions (2026-07) ────────────────────────────────────
  // One row per book. Stores full book introduction content for the study panel.
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS bible_book_introductions (
        id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        book_id             text NOT NULL UNIQUE,
        book_name           text NOT NULL DEFAULT '',
        testament           text NOT NULL DEFAULT '',
        genre               text NOT NULL DEFAULT '',
        author_attribution  text NOT NULL DEFAULT '',
        date_range          text NOT NULL DEFAULT '',
        original_audience   text NOT NULL DEFAULT '',
        historical_setting  text NOT NULL DEFAULT '',
        purpose             text NOT NULL DEFAULT '',
        major_themes        jsonb NOT NULL DEFAULT '[]',
        key_people          jsonb NOT NULL DEFAULT '[]',
        key_places          jsonb NOT NULL DEFAULT '[]',
        outline             jsonb NOT NULL DEFAULT '[]',
        key_passages        jsonb NOT NULL DEFAULT '[]',
        points_to_jesus     text NOT NULL DEFAULT '',
        interpretation_notes text NOT NULL DEFAULT '',
        status              text NOT NULL DEFAULT 'Draft'
          CHECK (status IN ('Draft','In Review','Published','Archived')),
        created_by          text NOT NULL DEFAULT '',
        updated_by          text NOT NULL DEFAULT '',
        created_at          timestamp NOT NULL DEFAULT now(),
        updated_at          timestamp NOT NULL DEFAULT now()
      )
    `);
    logger.info("Startup migration: bible_book_introductions table ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: bible_book_introductions table failed (non-fatal)");
  }

  // ── Bible: chapter overviews (2026-07) ─────────────────────────────────────
  // One row per book+chapter. Stores chapter-level summary for the study panel.
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS bible_chapter_overviews (
        id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        book_id             text NOT NULL,
        chapter             int  NOT NULL,
        UNIQUE (book_id, chapter),
        summary             text NOT NULL DEFAULT '',
        main_themes         jsonb NOT NULL DEFAULT '[]',
        important_people    jsonb NOT NULL DEFAULT '[]',
        important_locations jsonb NOT NULL DEFAULT '[]',
        passage_divisions   jsonb NOT NULL DEFAULT '[]',
        key_verse           text NOT NULL DEFAULT '',
        key_verse_start     int,
        key_verse_end       int,
        book_connection     text NOT NULL DEFAULT '',
        jesus_connection    text NOT NULL DEFAULT '',
        status              text NOT NULL DEFAULT 'Draft'
          CHECK (status IN ('Draft','In Review','Published','Archived')),
        created_by          text NOT NULL DEFAULT '',
        updated_by          text NOT NULL DEFAULT '',
        created_at          timestamp NOT NULL DEFAULT now(),
        updated_at          timestamp NOT NULL DEFAULT now()
      )
    `);
    logger.info("Startup migration: bible_chapter_overviews table ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: bible_chapter_overviews table failed (non-fatal)");
  }

  // ── Today's Steps: hide-from-today flag on devotional progress (2026-08) ──────
  // Replaces destructive "Remove" with a non-destructive hide. Progress, completed
  // days, and position are all preserved. The column defaults FALSE so existing
  // rows are unaffected.
  try {
    await pool.query(`
      ALTER TABLE devotional_progress
        ADD COLUMN IF NOT EXISTS hidden_from_today BOOLEAN NOT NULL DEFAULT FALSE
    `);
    logger.info("Startup migration: devotional_progress.hidden_from_today column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: devotional_progress.hidden_from_today failed (non-fatal)");
  }

  // ── Today's Steps: hide-from-today flag on sermon companion progress (2026-08) ─
  try {
    await pool.query(`
      ALTER TABLE sermon_companion_progress
        ADD COLUMN IF NOT EXISTS hidden_from_today BOOLEAN NOT NULL DEFAULT FALSE
    `);
    logger.info("Startup migration: sermon_companion_progress.hidden_from_today column ensured (idempotent)");
  } catch (err) {
    logger.warn({ err }, "Startup migration: sermon_companion_progress.hidden_from_today failed (non-fatal)");
  }

}
