/**
 * book-intros.ts — Static book introduction data
 *
 * Pre-seeded for all 66 books of the Protestant Bible.
 * Each entry provides author, approximate date, central theme, key verse,
 * and a short overview suitable for the reader intro card.
 *
 * Chapter overviews (one sentence per chapter) are seeded for the books
 * most actively used in the app (John, Luke, Romans, Psalms, etc.).
 */

export type BookIntro = {
  bookId: string;
  author: string;
  dateWritten: string;
  theme: string;
  keyVerse: string;
  keyVerseRef: string;
  overview: string;
};

export type ChapterOverview = {
  bookId: string;
  chapter: number;
  summary: string;
};

// ─── Book Introductions ───────────────────────────────────────────────────────

export const BOOK_INTROS: Record<string, BookIntro> = {
  genesis: {
    bookId: 'genesis',
    author: 'Moses',
    dateWritten: 'c. 1445–1405 BC',
    theme: 'Beginnings — creation, fall, redemption, and covenant',
    keyVerse: 'In the beginning God created the heavens and the earth.',
    keyVerseRef: 'Genesis 1:1',
    overview: 'Genesis is the book of beginnings. It opens with God creating the heavens and the earth, traces the origin of sin through Adam and Eve, and follows God\'s plan to rescue humanity through the covenant family of Abraham, Isaac, Jacob, and his twelve sons.',
  },
  exodus: {
    bookId: 'exodus',
    author: 'Moses',
    dateWritten: 'c. 1445–1405 BC',
    theme: 'Redemption and the Law',
    keyVerse: 'I am the LORD your God, who brought you out of Egypt, out of the house of slavery.',
    keyVerseRef: 'Exodus 20:2',
    overview: 'Exodus records God\'s dramatic rescue of Israel from Egyptian slavery, the giving of the Law at Sinai, and the construction of the Tabernacle. It reveals God as the great Redeemer who keeps his covenant promises.',
  },
  leviticus: {
    bookId: 'leviticus',
    author: 'Moses',
    dateWritten: 'c. 1445–1405 BC',
    theme: 'Holiness and atonement',
    keyVerse: 'Be holy because I, the LORD your God, am holy.',
    keyVerseRef: 'Leviticus 19:2',
    overview: 'Leviticus instructs Israel on how to approach a holy God through sacrifice, priesthood, and ritual purity. Every law points to the deeper truth that sin requires atonement — a theme fulfilled completely in Jesus Christ.',
  },
  numbers: {
    bookId: 'numbers',
    author: 'Moses',
    dateWritten: 'c. 1445–1405 BC',
    theme: 'Faithfulness vs. unbelief in the wilderness',
    keyVerse: 'The LORD bless you and keep you; the LORD make his face shine on you and be gracious to you.',
    keyVerseRef: 'Numbers 6:24–25',
    overview: 'Numbers follows Israel\'s 40-year journey through the wilderness, marked by census records, priestly laws, and repeated cycles of rebellion and grace. God disciplines his people while remaining committed to lead them to the Promised Land.',
  },
  deuteronomy: {
    bookId: 'deuteronomy',
    author: 'Moses',
    dateWritten: 'c. 1405 BC',
    theme: 'Covenant renewal and the call to love God',
    keyVerse: 'Love the LORD your God with all your heart and with all your soul and with all your strength.',
    keyVerseRef: 'Deuteronomy 6:5',
    overview: 'Deuteronomy records Moses\' final sermons to Israel before they enter Canaan. He calls the new generation to renew the covenant, love God wholeheartedly, and obey his commands — setting before them life and death, blessing and curse.',
  },
  joshua: {
    bookId: 'joshua',
    author: 'Joshua (largely)',
    dateWritten: 'c. 1405–1385 BC',
    theme: 'God\'s faithfulness to fulfil his promises',
    keyVerse: 'Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go.',
    keyVerseRef: 'Joshua 1:9',
    overview: 'Joshua narrates Israel\'s conquest and settlement of the Promised Land under Joshua\'s leadership. Every victory demonstrates that God is faithful to his covenant — the land is his gift, not Israel\'s achievement.',
  },
  judges: {
    bookId: 'judges',
    author: 'Unknown (possibly Samuel)',
    dateWritten: 'c. 1050–1000 BC',
    theme: 'The destructive cycle of sin, judgment, and deliverance',
    keyVerse: 'In those days Israel had no king; everyone did as they saw fit.',
    keyVerseRef: 'Judges 21:25',
    overview: 'Judges chronicles a dark period when Israel repeatedly abandoned God, fell into enemy hands, cried out for help, and was rescued by a series of Spirit-empowered judges. The book shows humanity\'s desperate need for a righteous king.',
  },
  ruth: {
    bookId: 'ruth',
    author: 'Unknown',
    dateWritten: 'c. 1000 BC',
    theme: 'Loyal love (hesed) and redemption',
    keyVerse: 'Where you go I will go, and where you stay I will stay. Your people will be my people and your God my God.',
    keyVerseRef: 'Ruth 1:16',
    overview: 'Ruth is a beautiful story of faithfulness, kindness, and redemption set in the time of the Judges. Through the kinsman-redeemer Boaz, Ruth finds belonging in Israel — and her story flows directly into the lineage of King David and Jesus.',
  },
  '1samuel': {
    bookId: '1samuel',
    author: 'Unknown (possibly Samuel, Nathan, Gad)',
    dateWritten: 'c. 930–722 BC',
    theme: 'The rise of monarchy — God\'s king vs. the people\'s king',
    keyVerse: 'The LORD does not look at the things people look at. People look at the outward appearance, but the LORD looks at the heart.',
    keyVerseRef: '1 Samuel 16:7',
    overview: '1 Samuel traces the transition from the era of judges to monarchy through three key figures: Samuel the last judge, Saul the failed king, and David the man after God\'s own heart. It shows what true leadership under God looks like.',
  },
  '2samuel': {
    bookId: '2samuel',
    author: 'Unknown',
    dateWritten: 'c. 930–722 BC',
    theme: 'The Davidic covenant and the cost of sin',
    keyVerse: 'Your house and your kingdom shall endure before me forever; your throne shall be established forever.',
    keyVerseRef: '2 Samuel 7:16',
    overview: '2 Samuel records David\'s reign as king of all Israel — his triumphs, the founding covenant God makes with him, and his catastrophic moral failures. Through David we see both the grace and the justice of God.',
  },
  '1kings': {
    bookId: '1kings',
    author: 'Unknown',
    dateWritten: 'c. 550 BC',
    theme: 'Wisdom, apostasy, and divided loyalty',
    keyVerse: 'How long will you waver between two opinions? If the LORD is God, follow him.',
    keyVerseRef: '1 Kings 18:21',
    overview: '1 Kings spans from Solomon\'s golden age to the division of the kingdom and the ministries of prophets like Elijah. It asks a fundamental question: will Israel remain faithful to their God, or chase after the nations\' idols?',
  },
  '2kings': {
    bookId: '2kings',
    author: 'Unknown',
    dateWritten: 'c. 550 BC',
    theme: 'Covenant consequences and the prophetic word',
    keyVerse: 'Yet the LORD was not willing to forgive the sins of Manasseh.',
    keyVerseRef: '2 Kings 24:4',
    overview: '2 Kings records the decline and fall of both Israel (exiled to Assyria) and Judah (exiled to Babylon). Despite the ministry of prophets including Elisha, the people persisted in covenant unfaithfulness until judgment came.',
  },
  '1chronicles': {
    bookId: '1chronicles',
    author: 'Ezra (traditionally)',
    dateWritten: 'c. 450–400 BC',
    theme: 'God\'s covenant with David and proper worship',
    keyVerse: 'Give praise to the LORD, proclaim his name; make known among the nations what he has done.',
    keyVerseRef: '1 Chronicles 16:8',
    overview: '1 Chronicles retells Israel\'s history from Adam to David, emphasising the Davidic covenant and the preparations for the Temple. Written for returned exiles, it calls them to remember God\'s faithfulness and restore proper worship.',
  },
  '2chronicles': {
    bookId: '2chronicles',
    author: 'Ezra (traditionally)',
    dateWritten: 'c. 450–400 BC',
    theme: 'True worship and the consequences of faithfulness or apostasy',
    keyVerse: 'If my people, who are called by my name, will humble themselves and pray and seek my face and turn from their wicked ways, then I will hear from heaven.',
    keyVerseRef: '2 Chronicles 7:14',
    overview: '2 Chronicles covers Solomon\'s reign and the history of Judah until exile and the Persian decree allowing return. Its central message: nations and kings rise or fall based on whether they honour God in worship and obedience.',
  },
  ezra: {
    bookId: 'ezra',
    author: 'Ezra',
    dateWritten: 'c. 457–444 BC',
    theme: 'Return, restoration, and covenant renewal',
    keyVerse: 'For Ezra had devoted himself to the study and observance of the Law of the LORD, and to teaching its decrees and laws in Israel.',
    keyVerseRef: 'Ezra 7:10',
    overview: 'Ezra records the return of Jewish exiles from Babylon and the rebuilding of the Temple in Jerusalem. It shows God fulfilling his word through pagan kings like Cyrus, and calls the community to separate themselves from compromise.',
  },
  nehemiah: {
    bookId: 'nehemiah',
    author: 'Nehemiah',
    dateWritten: 'c. 445–420 BC',
    theme: 'Rebuilding walls and renewing community',
    keyVerse: 'The God of heaven will give us success. We his servants will start rebuilding.',
    keyVerseRef: 'Nehemiah 2:20',
    overview: 'Nehemiah leads the final wave of exiles back to Jerusalem and oversees the rebuilding of the city walls. His story is a model of prayerful leadership — planning carefully, working faithfully, and defending against opposition.',
  },
  esther: {
    bookId: 'esther',
    author: 'Unknown',
    dateWritten: 'c. 486–465 BC',
    theme: 'God\'s hidden providence protecting his people',
    keyVerse: 'Who knows whether you have not come to the kingdom for such a time as this?',
    keyVerseRef: 'Esther 4:14',
    overview: 'Esther is set in the Persian court, where a young Jewish woman becomes queen and risks her life to save her people from genocide. Though God is never named, his providence is unmistakably woven through every event.',
  },
  job: {
    bookId: 'job',
    author: 'Unknown',
    dateWritten: 'Unknown (possibly patriarchal era)',
    theme: 'Suffering, faith, and the mystery of God\'s ways',
    keyVerse: 'I know that my redeemer lives, and that in the end he will stand on the earth.',
    keyVerseRef: 'Job 19:25',
    overview: 'Job wrestles with undeserved suffering through long dialogues with friends who offer inadequate answers. God\'s climactic response from the whirlwind doesn\'t explain the suffering but reveals that trusting God transcends human understanding.',
  },
  psalms: {
    bookId: 'psalms',
    author: 'Multiple — David (73), Asaph (12), Sons of Korah (11), Solomon (2), Moses (1), others',
    dateWritten: 'c. 1400–400 BC',
    theme: 'Worship, prayer, lament, and praise — the full range of life with God',
    keyVerse: 'The LORD is my shepherd; I lack nothing.',
    keyVerseRef: 'Psalm 23:1',
    overview: 'The Psalms are Israel\'s hymnbook — 150 poems and songs covering every human emotion before God. From shouts of praise to cries of desolation, the Psalms teach us that all of life can be brought honestly into God\'s presence.',
  },
  proverbs: {
    bookId: 'proverbs',
    author: 'Solomon (primarily), Agur, Lemuel',
    dateWritten: 'c. 970–700 BC',
    theme: 'Practical wisdom for godly living',
    keyVerse: 'The fear of the LORD is the beginning of wisdom, and knowledge of the Holy One is understanding.',
    keyVerseRef: 'Proverbs 9:10',
    overview: 'Proverbs collects wisdom for everyday life — from relationships, speech, and work, to money, family, and character. Its foundation is not a system of rules but a relationship: true wisdom begins with reverent trust in God.',
  },
  ecclesiastes: {
    bookId: 'ecclesiastes',
    author: 'Qoheleth ("the Teacher"), son of David',
    dateWritten: 'c. 935 BC',
    theme: 'The meaning of life under the sun',
    keyVerse: 'Now all has been heard; here is the conclusion of the matter: Fear God and keep his commandments, for this is the duty of all mankind.',
    keyVerseRef: 'Ecclesiastes 12:13',
    overview: 'Ecclesiastes is an honest, searching examination of life "under the sun." The Teacher concludes that wealth, pleasure, work, and wisdom all fail to satisfy on their own. Meaning is found only in fearing God and living in his gift of the present.',
  },
  songofsolomon: {
    bookId: 'songofsolomon',
    author: 'Solomon',
    dateWritten: 'c. 970–930 BC',
    theme: 'The beauty of love and intimacy',
    keyVerse: 'I am my beloved\'s and my beloved is mine.',
    keyVerseRef: 'Song of Solomon 6:3',
    overview: 'The Song of Solomon celebrates the beauty and joy of romantic love between a bride and groom. It has long been read as a picture of God\'s passionate love for his people — the intimacy he desires with those who belong to him.',
  },
  isaiah: {
    bookId: 'isaiah',
    author: 'Isaiah son of Amoz',
    dateWritten: 'c. 740–700 BC',
    theme: 'Judgment, comfort, and the coming Servant-King',
    keyVerse: 'But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his wounds we are healed.',
    keyVerseRef: 'Isaiah 53:5',
    overview: 'Isaiah is often called the "fifth Gospel" for its detailed prophecies of Christ. The book moves from announcements of judgment on unfaithful Israel to glorious visions of restoration through a Suffering Servant who bears sin on behalf of the many.',
  },
  jeremiah: {
    bookId: 'jeremiah',
    author: 'Jeremiah son of Hilkiah',
    dateWritten: 'c. 627–580 BC',
    theme: 'Judgment, lament, and the new covenant',
    keyVerse: '"This is the covenant I will make with the people of Israel after that time," declares the LORD. "I will put my law in their minds and write it on their hearts."',
    keyVerseRef: 'Jeremiah 31:33',
    overview: 'Jeremiah ministered during Judah\'s final decades before Babylonian exile, calling the nation to repentance. Though largely rejected, he announced a stunning new covenant where God would write his law on human hearts — fulfilled in Jesus.',
  },
  lamentations: {
    bookId: 'lamentations',
    author: 'Jeremiah (traditionally)',
    dateWritten: 'c. 586 BC',
    theme: 'Grief, confession, and hope in God\'s steadfast love',
    keyVerse: 'Because of the LORD\'s great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.',
    keyVerseRef: 'Lamentations 3:22–23',
    overview: 'Lamentations is a series of five poems mourning the destruction of Jerusalem by Babylon. Written in acrostic form, it takes grief seriously — and in the midst of desolation discovers that God\'s mercies never come to an end.',
  },
  ezekiel: {
    bookId: 'ezekiel',
    author: 'Ezekiel son of Buzi',
    dateWritten: 'c. 593–570 BC',
    theme: 'The glory of God, judgment, and restoration',
    keyVerse: 'I will give you a new heart and put a new spirit in you; I will remove from you your heart of stone and give you a heart of flesh.',
    keyVerseRef: 'Ezekiel 36:26',
    overview: 'Ezekiel ministered to Jewish exiles in Babylon, delivering vivid visions of God\'s glory, the reasons for judgment, and the breathtaking promise of restoration — including dry bones coming to life and a new Temple flowing with living water.',
  },
  daniel: {
    bookId: 'daniel',
    author: 'Daniel',
    dateWritten: 'c. 605–535 BC',
    theme: 'God\'s sovereignty over history and kingdoms',
    keyVerse: 'His kingdom is an eternal kingdom; his dominion endures from generation to generation.',
    keyVerseRef: 'Daniel 4:34',
    overview: 'Daniel records both the faithful lives of Jewish exiles at the Babylonian court and prophetic visions of world empires and the coming Son of Man. The book\'s message: no earthly power can stand against the kingdom of God.',
  },
  hosea: {
    bookId: 'hosea',
    author: 'Hosea son of Beeri',
    dateWritten: 'c. 755–715 BC',
    theme: 'God\'s relentless love for an unfaithful people',
    keyVerse: 'For I desire mercy, not sacrifice, and acknowledgment of God rather than burnt offerings.',
    keyVerseRef: 'Hosea 6:6',
    overview: 'God commands Hosea to marry an unfaithful woman as a living parable of Israel\'s spiritual adultery. Yet the book ends not with abandonment but with God\'s passionate call: "Return to me — my love for you will not give up."',
  },
  joel: {
    bookId: 'joel',
    author: 'Joel son of Pethuel',
    dateWritten: 'c. 835–800 BC',
    theme: 'The Day of the LORD — judgment and restoration',
    keyVerse: 'And afterward, I will pour out my Spirit on all people. Your sons and daughters will prophesy.',
    keyVerseRef: 'Joel 2:28',
    overview: 'A devastating locust plague becomes a prophetic image of the coming Day of the LORD. Joel calls for sincere repentance and promises that God will restore what the locusts have eaten — culminating in the outpouring of the Spirit at Pentecost.',
  },
  amos: {
    bookId: 'amos',
    author: 'Amos of Tekoa',
    dateWritten: 'c. 760–750 BC',
    theme: 'Justice and the righteousness God demands',
    keyVerse: 'But let justice roll on like a river, righteousness like a never-failing stream!',
    keyVerseRef: 'Amos 5:24',
    overview: 'Amos, a shepherd from the south, delivers a searing indictment against wealthy Israel for oppressing the poor. Religious ritual without social justice is an abomination to God — true worship overflows into how we treat the vulnerable.',
  },
  obadiah: {
    bookId: 'obadiah',
    author: 'Obadiah',
    dateWritten: 'c. 586 BC',
    theme: 'Judgment on pride and betrayal',
    keyVerse: 'The day of the LORD is near for all nations. As you have done, it will be done to you.',
    keyVerseRef: 'Obadiah 1:15',
    overview: 'The shortest book of the Old Testament pronounces judgment on Edom — Esau\'s descendants — for gloating over Jerusalem\'s fall and betraying their brother Jacob. The book ends with the assurance that the kingdom will belong to the LORD.',
  },
  jonah: {
    bookId: 'jonah',
    author: 'Jonah son of Amittai',
    dateWritten: 'c. 785–760 BC',
    theme: 'God\'s mercy extends beyond Israel',
    keyVerse: 'I knew that you are a gracious and compassionate God, slow to anger and abounding in love.',
    keyVerseRef: 'Jonah 4:2',
    overview: 'Jonah\'s reluctant mission to Nineveh reveals both the scope of God\'s compassion and the prophet\'s own prejudice. When the entire city repents, God spares them — and Jonah\'s angry reaction becomes a mirror for our own hearts.',
  },
  micah: {
    bookId: 'micah',
    author: 'Micah of Moresheth',
    dateWritten: 'c. 735–700 BC',
    theme: 'Justice, mercy, and hope for the remnant',
    keyVerse: 'He has shown you, O mortal, what is good. And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God.',
    keyVerseRef: 'Micah 6:8',
    overview: 'Micah alternates between oracles of judgment and promises of restoration, culminating in the famous verse defining true religion. He also prophesies that Israel\'s ruler will come from Bethlehem — a prophecy fulfilled in Jesus.',
  },
  nahum: {
    bookId: 'nahum',
    author: 'Nahum the Elkoshite',
    dateWritten: 'c. 663–612 BC',
    theme: 'The justice of God against Nineveh\'s violence',
    keyVerse: 'The LORD is good, a refuge in times of trouble. He cares for those who trust in him.',
    keyVerseRef: 'Nahum 1:7',
    overview: 'A century after Jonah, Nahum announces the coming destruction of Nineveh, the Assyrian capital. The book assures God\'s people that oppressive powers do not have the last word — the God who is slow to anger will also act in righteous judgment.',
  },
  habakkuk: {
    bookId: 'habakkuk',
    author: 'Habakkuk',
    dateWritten: 'c. 612–605 BC',
    theme: 'Wrestling with God and finding faith',
    keyVerse: 'The righteous person will live by his faithfulness.',
    keyVerseRef: 'Habakkuk 2:4',
    overview: 'Habakkuk dares to question God — why does evil go unpunished? God\'s answers raise harder questions, but the prophet\'s journey ends in a breathtaking psalm of trust. The book pioneered the doctrine later expounded by Paul: the righteous shall live by faith.',
  },
  zephaniah: {
    bookId: 'zephaniah',
    author: 'Zephaniah son of Cushi',
    dateWritten: 'c. 640–612 BC',
    theme: 'The Day of the LORD and the joy of restoration',
    keyVerse: 'The LORD your God is with you, the Mighty Warrior who saves. He will take great delight in you.',
    keyVerseRef: 'Zephaniah 3:17',
    overview: 'Zephaniah proclaims a devastating Day of the LORD before pivoting to one of the most tender passages in the Old Testament — God singing over his restored people with joy. Judgment and grace are held together in one short book.',
  },
  haggai: {
    bookId: 'haggai',
    author: 'Haggai',
    dateWritten: 'c. 520 BC',
    theme: 'Prioritise God\'s house and God will bless you',
    keyVerse: '"The glory of this present house will be greater than the glory of the former house," says the LORD Almighty.',
    keyVerseRef: 'Haggai 2:9',
    overview: 'Haggai delivers four short sermons challenging returned exiles who have neglected the Temple rebuilding. The book connects misplaced priorities with fruitlessness — and promises a greater glory ahead for those who put God first.',
  },
  zechariah: {
    bookId: 'zechariah',
    author: 'Zechariah son of Berekiah',
    dateWritten: 'c. 520–480 BC',
    theme: 'Messianic hope and the coming King',
    keyVerse: 'Rejoice greatly, Daughter Zion! Shout, Daughter Jerusalem! See, your king comes to you, righteous and victorious, lowly and riding on a donkey.',
    keyVerseRef: 'Zechariah 9:9',
    overview: 'Zechariah encourages Temple rebuilding through visions, oracles, and Messianic prophecy — including the king entering Jerusalem on a donkey and the Shepherd being struck. More of his prophecies are quoted in the Passion narratives than any other Old Testament book.',
  },
  malachi: {
    bookId: 'malachi',
    author: 'Malachi',
    dateWritten: 'c. 430 BC',
    theme: 'Return to the LORD before the Day of Judgment',
    keyVerse: '"Return to me, and I will return to you," says the LORD Almighty.',
    keyVerseRef: 'Malachi 3:7',
    overview: 'The last prophetic book of the Old Testament addresses a complacent post-exilic community. Through six disputes, God challenges Israel\'s half-hearted worship, covenant breaking, and doubt — and promises to send a messenger to prepare his coming.',
  },
  matthew: {
    bookId: 'matthew',
    author: 'Matthew (Levi), an apostle',
    dateWritten: 'c. AD 50–70',
    theme: 'Jesus as the fulfillment of Israel\'s story — the King of the Kingdom',
    keyVerse: 'Therefore go and make disciples of all nations, baptising them in the name of the Father and of the Son and of the Holy Spirit.',
    keyVerseRef: 'Matthew 28:19',
    overview: 'Matthew presents Jesus as the long-awaited Messiah who fulfils every promise of the Old Testament. Written for a Jewish audience, it traces Jesus as prophet, priest, and king — and culminates in his commission to take the good news to all nations.',
  },
  mark: {
    bookId: 'mark',
    author: 'John Mark (companion of Peter)',
    dateWritten: 'c. AD 55–65',
    theme: 'Jesus as the powerful Servant — the Son of God in action',
    keyVerse: 'For even the Son of Man did not come to be served, but to serve, and to give his life as a ransom for many.',
    keyVerseRef: 'Mark 10:45',
    overview: 'The shortest and most fast-paced Gospel, Mark presents Jesus as the divine Servant who acts with authority over demons, disease, and death. Nearly half the book focuses on the last week of Jesus\' life, underscoring that the cross is the centre of his mission.',
  },
  luke: {
    bookId: 'luke',
    author: 'Luke — physician and companion of Paul',
    dateWritten: 'c. AD 60–62',
    theme: 'Jesus the Saviour of all people',
    keyVerse: 'For the Son of Man came to seek and to save the lost.',
    keyVerseRef: 'Luke 19:10',
    overview: 'The Gospel of Luke presents the most complete account of the life of Jesus. Written for all people — not just Jews — Luke shows Jesus healing the broken, welcoming the outcast, and dining with sinners. He came to seek and to save the lost.',
  },
  john: {
    bookId: 'john',
    author: 'John, the apostle',
    dateWritten: 'c. AD 85–95',
    theme: 'Believe that Jesus is the Son of God and receive eternal life',
    keyVerse: 'For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.',
    keyVerseRef: 'John 3:16',
    overview: 'The Gospel of John presents Jesus as the eternal Word of God made flesh. Written explicitly so you may believe that Jesus is the Messiah, John records seven "I AM" declarations, seven signs, and intimate conversations with individuals — all pointing to one conclusion: Jesus is Lord.',
  },
  acts: {
    bookId: 'acts',
    author: 'Luke — physician and companion of Paul',
    dateWritten: 'c. AD 62',
    theme: 'The Spirit-empowered expansion of the church to the ends of the earth',
    keyVerse: 'But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.',
    keyVerseRef: 'Acts 1:8',
    overview: 'Acts records the birth and expansion of the early church from Jerusalem to Rome, driven by the power of the Holy Spirit. Through Peter, Paul, and many others, the gospel breaks every barrier — ethnic, cultural, and geographic.',
  },
  romans: {
    bookId: 'romans',
    author: 'The Apostle Paul',
    dateWritten: 'c. AD 57',
    theme: 'The righteousness of God revealed through faith in Jesus Christ',
    keyVerse: 'For I am not ashamed of the gospel, because it is the power of God that brings salvation to everyone who believes.',
    keyVerseRef: 'Romans 1:16',
    overview: 'Romans is Paul\'s most systematic presentation of the gospel. He argues that all people — Jew and Gentile — are under sin, but God\'s righteousness is freely given through faith in Jesus Christ. The letter climaxes in a vision of life in the Spirit and the renewed community.',
  },
  '1corinthians': {
    bookId: '1corinthians',
    author: 'The Apostle Paul',
    dateWritten: 'c. AD 53–54',
    theme: 'The cross as the wisdom of God for a divided church',
    keyVerse: 'For the message of the cross is foolishness to those who are perishing, but to us who are being saved it is the power of God.',
    keyVerseRef: '1 Corinthians 1:18',
    overview: 'Paul writes to address a fractured, worldly church in Corinth, covering division, sexual immorality, spiritual gifts, and the resurrection. The cross is the recurring answer — its wisdom and power reshape every area of church life and personal ethics.',
  },
  '2corinthians': {
    bookId: '2corinthians',
    author: 'The Apostle Paul',
    dateWritten: 'c. AD 55–56',
    theme: 'Strength through weakness — the paradox of apostolic ministry',
    keyVerse: 'My grace is sufficient for you, for my power is made perfect in weakness.',
    keyVerseRef: '2 Corinthians 12:9',
    overview: 'The most personal of Paul\'s letters, 2 Corinthians defends his apostleship against critics while revealing the paradox at the heart of the gospel: God\'s power is most visible precisely when human strength runs out.',
  },
  galatians: {
    bookId: 'galatians',
    author: 'The Apostle Paul',
    dateWritten: 'c. AD 48–50',
    theme: 'Freedom through faith alone in Christ alone',
    keyVerse: 'It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.',
    keyVerseRef: 'Galatians 5:1',
    overview: 'Galatians is Paul\'s most urgent letter, written to churches returning to law-keeping as a means of justification. Paul insists that justification is by faith alone — adding anything to Christ is to abandon the gospel entirely. True freedom comes from the Spirit, not law.',
  },
  ephesians: {
    bookId: 'ephesians',
    author: 'The Apostle Paul',
    dateWritten: 'c. AD 60–62',
    theme: 'The riches of life in Christ and the mystery of the Church',
    keyVerse: 'For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God.',
    keyVerseRef: 'Ephesians 2:8',
    overview: 'Ephesians soars with praise for what God has done in Christ — uniting Jew and Gentile in one body, the Church. The letter moves from doxology to duty: because of your identity in Christ, walk worthy of your calling in every relationship.',
  },
  philippians: {
    bookId: 'philippians',
    author: 'The Apostle Paul',
    dateWritten: 'c. AD 61',
    theme: 'Joy and contentment in all circumstances through Christ',
    keyVerse: 'I can do all this through him who gives me strength.',
    keyVerseRef: 'Philippians 4:13',
    overview: 'Written from prison, Philippians is Paul\'s most joyful letter. He urges the church to maintain unity, embrace the humility of Christ, and fix their minds on what is true and good. Joy is not circumstantial — it is rooted in knowing Christ.',
  },
  colossians: {
    bookId: 'colossians',
    author: 'The Apostle Paul',
    dateWritten: 'c. AD 60–62',
    theme: 'The supremacy and sufficiency of Christ',
    keyVerse: 'For in Christ all the fullness of the Deity lives in bodily form, and in Christ you have been brought to fullness.',
    keyVerseRef: 'Colossians 2:9–10',
    overview: 'Against the influence of empty philosophy and mystical additions to faith, Paul presents the absolute supremacy of Jesus: he is the image of the invisible God, the head of the church, and in him all wisdom and knowledge are hidden. Nothing needs to be added to Christ.',
  },
  '1thessalonians': {
    bookId: '1thessalonians',
    author: 'The Apostle Paul',
    dateWritten: 'c. AD 50–51',
    theme: 'Living in light of Christ\'s return',
    keyVerse: 'For the Lord himself will come down from heaven... and the dead in Christ will rise first.',
    keyVerseRef: '1 Thessalonians 4:16',
    overview: 'Paul\'s first letter to the Thessalonians commends their faith and encourages them about believers who have died. The return of Christ is not a cause for grief but a source of hope — and it should shape how we live every day.',
  },
  '2thessalonians': {
    bookId: '2thessalonians',
    author: 'The Apostle Paul',
    dateWritten: 'c. AD 51–52',
    theme: 'Standing firm until the Day of the Lord',
    keyVerse: 'May the Lord direct your hearts into God\'s love and Christ\'s perseverance.',
    keyVerseRef: '2 Thessalonians 3:5',
    overview: 'Paul corrects misunderstandings about Christ\'s return that had led some to stop working. He assures the church that the Day of the Lord has not yet come, urges steadfastness under persecution, and calls for gospel-shaped community life.',
  },
  '1timothy': {
    bookId: '1timothy',
    author: 'The Apostle Paul',
    dateWritten: 'c. AD 62–64',
    theme: 'Healthy church life and sound doctrine',
    keyVerse: 'Here is a trustworthy saying that deserves full acceptance: Christ Jesus came into the world to save sinners.',
    keyVerseRef: '1 Timothy 1:15',
    overview: 'Paul writes to his young delegate Timothy in Ephesus, instructing him on church leadership, prayer, sound teaching, and godly conduct. The letter is a manual for building a healthy church in the face of false teaching.',
  },
  '2timothy': {
    bookId: '2timothy',
    author: 'The Apostle Paul',
    dateWritten: 'c. AD 67',
    theme: 'Faithful endurance to the end',
    keyVerse: 'I have fought the good fight, I have finished the race, I have kept the faith.',
    keyVerseRef: '2 Timothy 4:7',
    overview: 'Paul\'s final letter, written from prison awaiting execution. He urges Timothy to guard the gospel, endure hardship, and finish his own race well. The letter is a charge from a dying apostle to the next generation: the gospel is worth everything.',
  },
  titus: {
    bookId: 'titus',
    author: 'The Apostle Paul',
    dateWritten: 'c. AD 63–65',
    theme: 'Sound doctrine must produce godly living',
    keyVerse: 'For the grace of God has appeared that offers salvation to all people. It teaches us to say "No" to ungodliness and worldly passions.',
    keyVerseRef: 'Titus 2:11–12',
    overview: 'Paul writes to Titus in Crete about appointing elders and reforming behaviour. The gospel is not merely doctrinal but transformational — God\'s saving grace produces a people who are eager to do what is good.',
  },
  philemon: {
    bookId: 'philemon',
    author: 'The Apostle Paul',
    dateWritten: 'c. AD 60–62',
    theme: 'The gospel transforms relationships — even slavery',
    keyVerse: 'Perhaps the reason he was separated from you for a little while was that you might have him back forever — no longer as a slave, but better than a slave, as a dear brother.',
    keyVerseRef: 'Philemon 1:15–16',
    overview: 'The shortest of Paul\'s letters is a personal appeal to Philemon to receive his runaway slave Onesimus back as a brother in Christ. Paul leverages the gospel to redefine a social institution — love and forgiveness are more powerful than law.',
  },
  hebrews: {
    bookId: 'hebrews',
    author: 'Unknown (possibly Apollos, Barnabas, or a Pauline associate)',
    dateWritten: 'c. AD 60–70',
    theme: 'Jesus as the superior fulfilment of everything in the Old Covenant',
    keyVerse: 'The Son is the radiance of God\'s glory and the exact representation of his being, sustaining all things by his powerful word.',
    keyVerseRef: 'Hebrews 1:3',
    overview: 'Hebrews is a sustained argument that Jesus is superior to every element of the Old Covenant — angels, Moses, the Aaronic priesthood, and the sacrificial system. The letter urges Jewish Christians not to turn back but to fix their eyes on Jesus, the pioneer and perfecter of faith.',
  },
  james: {
    bookId: 'james',
    author: 'James, brother of Jesus',
    dateWritten: 'c. AD 45–49',
    theme: 'Living faith must produce visible action',
    keyVerse: 'Faith by itself, if it is not accompanied by action, is dead.',
    keyVerseRef: 'James 2:17',
    overview: 'James is intensely practical — a New Testament Proverbs. He challenges his readers on trials, favouritism, the tongue, prayer, and wisdom. Faith that does not change behaviour is not genuine faith at all.',
  },
  '1peter': {
    bookId: '1peter',
    author: 'The Apostle Peter',
    dateWritten: 'c. AD 62–64',
    theme: 'Suffering as a pilgrim people with a living hope',
    keyVerse: 'In his great mercy he has given us new birth into a living hope through the resurrection of Jesus Christ from the dead.',
    keyVerseRef: '1 Peter 1:3',
    overview: 'Peter writes to scattered Christians facing persecution, calling them to live as holy strangers in the world. Their suffering has meaning — just as Christ suffered before entering glory, so his followers suffer before their eternal inheritance.',
  },
  '2peter': {
    bookId: '2peter',
    author: 'The Apostle Peter',
    dateWritten: 'c. AD 65–68',
    theme: 'Guard against false teachers and grow in grace',
    keyVerse: 'Grow in the grace and knowledge of our Lord and Saviour Jesus Christ.',
    keyVerseRef: '2 Peter 3:18',
    overview: 'Peter\'s second letter warns urgently against false teachers who deny the Lord\'s return and exploit the church. In response, believers must grow in moral virtue, deepen their knowledge of Christ, and hold fast to the prophetic word.',
  },
  '1john': {
    bookId: '1john',
    author: 'John, the apostle',
    dateWritten: 'c. AD 85–95',
    theme: 'Assurance of eternal life through genuine love and right belief',
    keyVerse: 'God is love. Whoever lives in love lives in God, and God in them.',
    keyVerseRef: '1 John 4:16',
    overview: '1 John was written so believers can know they have eternal life. John gives three tests of genuine faith: believing the truth about Jesus, obeying God\'s commands, and loving one another. These are not conditions for salvation but marks of the one who truly belongs to God.',
  },
  '2john': {
    bookId: '2john',
    author: 'John, the apostle',
    dateWritten: 'c. AD 90',
    theme: 'Walk in love; guard the truth',
    keyVerse: 'And now, dear lady, I am not writing you a new command but one we have had from the beginning. I ask that we love one another.',
    keyVerseRef: '2 John 1:5',
    overview: 'The shortest book in the New Testament urges a local church to continue walking in love while refusing hospitality to teachers who deny the incarnation. Love and truth must never be separated — each without the other is incomplete.',
  },
  '3john': {
    bookId: '3john',
    author: 'John, the apostle',
    dateWritten: 'c. AD 90',
    theme: 'Support gospel workers; do not imitate evil',
    keyVerse: 'Dear friend, do not imitate what is evil but what is good. Anyone who does what is good is from God.',
    keyVerseRef: '3 John 1:11',
    overview: '3 John commends Gaius for welcoming travelling missionaries and rebukes Diotrephes for his self-promoting opposition to them. The letter shows how local church dynamics have always mattered for global gospel advance.',
  },
  jude: {
    bookId: 'jude',
    author: 'Jude, brother of Jesus',
    dateWritten: 'c. AD 65',
    theme: 'Contend earnestly for the faith against ungodly intruders',
    keyVerse: 'To him who is able to keep you from stumbling and to present you before his glorious presence without fault and with great joy.',
    keyVerseRef: 'Jude 1:24',
    overview: 'Jude sounds an urgent alarm about false teachers who have crept into the church, calling believers to contend for the faith. But the letter ends with one of the most majestic doxologies in the Bible, reminding us that our standing before God rests on his power, not ours.',
  },
  revelation: {
    bookId: 'revelation',
    author: 'John, the apostle',
    dateWritten: 'c. AD 95–96',
    theme: 'The victory of the Lamb and the renewal of all things',
    keyVerse: '"I am the Alpha and the Omega," says the Lord God, "who is, and who was, and who is to come, the Almighty."',
    keyVerseRef: 'Revelation 1:8',
    overview: 'Revelation is a letter of apocalyptic visions given to seven persecuted churches in Asia Minor. Its central message is hope: despite appearances, the Lamb who was slain has conquered, and every tear will one day be wiped away when God makes all things new.',
  },
};

// ─── Chapter Overviews ────────────────────────────────────────────────────────
// One-sentence "chapter at a glance" for key books. Pre-seeded for John and Luke
// (primary books in the app). Admins can extend via the database.

export const CHAPTER_OVERVIEWS: Record<string, string> = {
  // John
  'john:1':  'The eternal Word becomes flesh, John the Baptist testifies about the coming light, and Jesus calls his first disciples.',
  'john:2':  'Jesus turns water into wine at a wedding in Cana and cleanses the Temple in Jerusalem — two dramatic signs of the new era he is inaugurating.',
  'john:3':  'Jesus tells Nicodemus that new birth by the Spirit is essential, and John summarises the gospel: "For God so loved the world…"',
  'john:4':  'Jesus offers living water to a Samaritan woman at a well and heals a royal official\'s son — signs that he is the Saviour of the world, not just Israel.',
  'john:5':  'Jesus heals a lame man on the Sabbath and defends his authority as the Son who gives life — claiming equality with his Father.',
  'john:6':  'Jesus feeds five thousand, walks on water, and teaches that he is the Bread of Life — the crowd must eat his flesh and drink his blood to have eternal life.',
  'john:7':  'At the Feast of Tabernacles Jesus openly teaches in the Temple, divided opinion about his identity escalating toward a crisis.',
  'john:8':  'Jesus declares himself the Light of the World and confronts the Pharisees over their spiritual heritage, culminating in the stunning claim "Before Abraham was, I AM."',
  'john:9':  'Jesus gives sight to a man born blind, then reveals that the real blindness belongs to those who claim they can see but refuse to believe.',
  'john:10': 'Jesus announces himself as the Good Shepherd who lays down his life for his sheep and as the gate through which his sheep find life.',
  'john:11': 'Jesus raises Lazarus from the dead four days after his burial — his greatest sign yet, and the act that finally triggers the plot to kill him.',
  'john:12': 'Mary anoints Jesus for burial, the crowds welcome him into Jerusalem on a donkey, and Jesus declares that the hour of glorification through death has come.',
  'john:13': 'Jesus washes his disciples\' feet, predicts his betrayal, and gives them a new commandment: love one another as I have loved you.',
  'john:14': 'Jesus comforts his disciples with the promise of the Father\'s house, reveals that he is the way, the truth, and the life, and promises the coming Holy Spirit.',
  'john:15': 'Jesus teaches about abiding in him as the true vine, the love that flows between the Father, Son, and disciples, and the world\'s inevitable hatred.',
  'john:16': 'Jesus prepares his disciples for his departure, promises that the Spirit will convict the world and guide them into all truth, and assures them: "I have overcome the world."',
  'john:17': 'Jesus prays for himself, for his disciples, and for all who will believe — that they may be one, even as the Father and Son are one.',
  'john:18': 'Jesus is betrayed and arrested in Gethsemane, Peter denies him three times, and Jesus stands before Pilate who finds no basis for a charge.',
  'john:19': 'Jesus is crucified at Golgotha, declares "It is finished", and is buried in a nearby garden tomb.',
  'john:20': 'Mary Magdalene and the disciples discover the empty tomb; the risen Jesus appears to Mary, to his disciples, and to Thomas — "My Lord and my God!"',
  'john:21': 'Jesus appears by the Sea of Galilee, provides a miraculous catch of fish, restores Peter with three questions of love, and sends him to feed his sheep.',

  // Luke
  'luke:1':  'The angel Gabriel announces the births of John the Baptist and Jesus; Mary sings the Magnificat and Zechariah prophesies about the coming dawn from on high.',
  'luke:2':  'Jesus is born in Bethlehem, welcomed by shepherds and angelic praise, presented at the Temple, and as a twelve-year-old found discussing Scripture with teachers.',
  'luke:3':  'John the Baptist preaches repentance and baptism in the Jordan, Jesus is baptised and the Spirit descends, and his genealogy is traced back to Adam — the Son of God.',
  'luke:4':  'Jesus resists Satan\'s temptations in the wilderness, announces his mission in Nazareth ("to proclaim good news to the poor"), and demonstrates his authority over demons and disease.',
  'luke:5':  'Jesus calls Simon Peter from his fishing boat, cleanses a leper, heals a paralysed man let down through a roof, and invites Levi the tax collector to follow him.',
  'luke:6':  'Jesus chooses twelve apostles, teaches the Beatitudes and the Sermon on the Plain, and calls his followers to radical love — even for enemies.',
  'luke:7':  'Jesus heals a centurion\'s servant, raises a widow\'s son, commends John the Baptist, and allows a sinful woman to anoint his feet — a picture of lavish forgiveness.',
  'luke:8':  'The parable of the sower, Jesus calming the storm, healing a demon-possessed man, raising Jairus\' daughter — signs that Jesus has authority over every power.',
  'luke:9':  'Jesus sends out the twelve, feeds five thousand, is transfigured on a mountain, and begins to tell his disciples plainly: "The Son of Man must suffer many things."',
  'luke:10': 'Jesus sends seventy-two disciples ahead of him, tells the parable of the Good Samaritan, and commends Mary for choosing "the better part."',
  'luke:11': 'Jesus teaches the Lord\'s Prayer, warns about spiritual emptiness, pronounces woes against the Pharisees for honouring prophets they would have killed.',
  'luke:12': 'Jesus warns against hypocrisy and greed, tells the parable of the rich fool, urges readiness for his return, and says he came to bring fire — not peace — to the earth.',
  'luke:13': 'Jesus calls the nation to repentance, heals a crippled woman on the Sabbath, uses the mustard seed and yeast parables, and laments over Jerusalem.',
  'luke:14': 'Jesus heals on the Sabbath, teaches about humility at banquets, tells the parable of the great banquet, and counts the cost of discipleship.',
  'luke:15': 'Three parables of lostness: the lost sheep, the lost coin, and the prodigal son — each ending with celebration that mirrors the joy in heaven over one sinner who repents.',
  'luke:16': 'The parable of the shrewd manager, teaching on wealth and faithfulness, and the story of the rich man and Lazarus — a warning about where earthly comfort leads.',
  'luke:17': 'Jesus teaches on forgiveness, faith, servanthood, and gratitude (the one leper who returned), and warns that the coming of the Kingdom will be sudden and unmistakable.',
  'luke:18': 'The persistent widow, the Pharisee and the tax collector, Jesus welcoming children, the rich young ruler, a third passion prediction, and the healing of blind Bartimaeus.',
  'luke:19': 'Zacchaeus the tax collector is saved; Jesus enters Jerusalem on a donkey to shouts of hosanna; he weeps over the city and cleanses the Temple.',
  'luke:20': 'The chief priests challenge Jesus\' authority; he responds with the parable of the tenants, the question about Caesar\'s coin, and the question about David\'s Lord.',
  'luke:21': 'Jesus commends the widow\'s offering, predicts the Temple\'s destruction, warns of cosmic signs before his return, and urges watchfulness.',
  'luke:22': 'The Last Supper, Jesus\' prayer in Gethsemane, his arrest, Peter\'s denial, and his trial before the Sanhedrin.',
  'luke:23': 'Jesus is tried by Pilate and Herod, crucified alongside two criminals, dies commending his spirit to the Father, and is buried in Joseph of Arimathea\'s tomb.',
  'luke:24': 'The empty tomb, the road to Emmaus, Jesus\' appearance to the disciples, his commissioning of witnesses, and his ascension from Bethany.',

  // Romans
  'romans:1':  'Paul introduces himself and the gospel: God\'s power for salvation to all who believe — and his wrath against all who suppress the truth.',
  'romans:2':  'Paul warns that Jews who judge others while breaking the law themselves are equally accountable — true circumcision is of the heart.',
  'romans:3':  'All — Jew and Gentile — are under sin; but God\'s righteousness is revealed through faith in Jesus Christ, whose death was the atoning sacrifice for sin.',
  'romans:4':  'Abraham was declared righteous by faith before circumcision — making him the father of all who believe, not just the circumcised.',
  'romans:5':  'Because we are justified by faith we have peace with God; and just as sin and death came through Adam, so grace and life come through the one man Jesus Christ.',
  'romans:6':  'Baptised into Christ\'s death and resurrection, believers are freed from slavery to sin — dead to sin and alive to God in Christ Jesus.',
  'romans:7':  'Paul wrestles with the inner conflict of wanting to obey the law but finding sin at work within him — a conflict that points to the need for the Spirit.',
  'romans:8':  'The Spirit sets believers free from condemnation, adopts them as children of God, intercedes in their weakness, and assures them that nothing can separate them from God\'s love.',
  'romans:9':  'Paul grieves for Israel and defends God\'s sovereign freedom to show mercy to whom he chooses — his purposes have not failed.',
  'romans:10': 'Righteousness comes through confessing and believing in Jesus; and since "everyone who calls on the name of the Lord will be saved," the gospel must be proclaimed.',
  'romans:11': 'Israel\'s stumbling has opened the door to the Gentiles, but God has not rejected his people — and Paul closes with a hymn to the unsearchable depths of God\'s wisdom.',
  'romans:12': 'In view of God\'s mercy, offer yourself as a living sacrifice; use your gifts in the body; and overcome evil with good.',
  'romans:13': 'Submit to governing authorities, owe nothing but love, and clothe yourself with the Lord Jesus Christ — for salvation is nearer than when you first believed.',
  'romans:14': 'Accept those whose faith is weak; do not judge one another on disputable matters; for the Kingdom is not about eating and drinking but righteousness, peace, and joy in the Spirit.',
  'romans:15': 'Accept one another as Christ accepted you; Paul shares his ambition to preach where Christ is not known and his plan to visit Rome on the way to Spain.',
  'romans:16': 'Paul greets many co-workers by name, warns against divisive teachers, and ends with a doxology to God who can establish his people according to the gospel.',
};
